### ISSUE TITLE
Intermittent "Could not create SSL/TLS secure channel" error when sending mail

### ISSUE THREAD

**Issue by kkennedy1** [sendgrid/sendgrid-csharp#100]
We are currently getting intermittent "Could not create SSL/TLS secure channel" errors when sending email through SendGrid.  We are using the .NET C# library 1.1.0.0.  Here is the code we are using:

Web mailer = SendGridMail.Transport.Web.GetInstanace(new NetworkCredential(username, password))
mailer.Deliver(message) // message is ISendGrid

This is intermittent where it seems like the first time a message is sent, it fails, but the second time it works fine.  We recently updated our SSL cert to be SHA256.  Not sure if that has anything to do with this issue or not.

Thanks!

**Comment by brandonmwest** [comment]
Version 1.1.0 is pretty old. The current version is 5.0.0. We did make a change to disable SSLv3 on our API endpoints due to the POODLE vulnerability which might cause something to break in older versions, but it's hard to say. If you can upgrade to the latest version, which would require some work on your part since there were several breaking changes, hopefully your issues will stop or we'll be able to isolate them.

**Comment by jonhel** [comment]
Remove Ssl3 from ServicePointManager.SecurityProtocol by setting it to:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

The default value is SecurityProtocolType.Tls | SecurityProtocol.Ssl3 which is probably causing you issues.

Or upgrade your references to SendGrid (seems to be fixed in the latest version).

**Comment by kkennedy1** [comment]
Thank you.  We’ve updated to version 5 and the issue appears to be taken care of.
