### ISSUE TITLE
Do not introduce breaking changes in minor versions

### ISSUE THREAD

**Issue by janousek** [sendgrid/sendgrid-csharp#1000]
### Issue Summary
Version 9.15.0 contains undocumented breaking changes in SendGridCient. Now it is impossible to pass own configuration using SendGridClientOptions.  Because of this it is impossible to set some of options avaiable in SendGridClientOptions (for example ReliabilitySettings).

And now I discovered that ReliabilitySettings is totaly ignored (it is hardcoded):
https://github.com/sendgrid/sendgrid-csharp/blob/cf618490bbb556e400b90f0360e4f9eadc6e2bca/src/SendGrid/BaseClient.cs#L226
https://github.com/sendgrid/sendgrid-csharp/blob/cf618490bbb556e400b90f0360e4f9eadc6e2bca/src/SendGrid/BaseClient.cs#L245

This is shame. Your developers should really think about changes that they make (merget to master branch) before you publish new version. You are breaking existing code.

**Comment by childish-sambino** [comment]
So this is the old line:
https://github.com/sendgrid/sendgrid-csharp/blob/908074cf53ea4fa188edf6b0772909d3a67b03e1/src/SendGrid/SendGridClient.cs#L275

It uses `DefaultOptions` which was defined here:
https://github.com/sendgrid/sendgrid-csharp/blob/908074cf53ea4fa188edf6b0772909d3a67b03e1/src/SendGrid/SendGridClient.cs#L39

How were you able to modify the `ReliabilitySettings` of `DefaultOptions`? I don't see any accessors for `DefaultOptions` or its `ReliabilitySettings` (when looking at the code before the changes in question).

**Comment by janousek** [comment]
ReliabilitySettings  gets broken in this commit:
https://github.com/sendgrid/sendgrid-csharp/commit/d6c2349a7b10b59ef81dd1e177e684276e785f77

**Comment by childish-sambino** [comment]
Ahhh, perfect. Thanks! So it's been broken since `9.11.0` and now I understand why it was the way it was before I refactored things in #997. I tried hard to not break the interface, but turns out it was already borked. I'll work on a fix. Thanks for bringing this to our attention!

And just to be clear, you're basically wanting this constructor back so you can pass in your own `SendGridClientOptions` instance?
https://github.com/sendgrid/sendgrid-csharp/blob/2310b6e98cbff8405fef3d5ab891911e492ae431/src/SendGrid/SendGridClient.cs#L68-L76
