### ISSUE TITLE
Error code 406 NotAcceptable

### ISSUE THREAD

**Issue by DHFerraz** [sendgrid/sendgrid-csharp#1002]
I have two requests to SendGrid API that are return an error not mapped in API docs. The error is "406 Not Acceptable". But it just happening in production environment, when I testing locally, everything works.

The requests are:
POST access_settings/whitelist
POST mail/batch

![image](https://user-images.githubusercontent.com/29411685/82063879-6f09c100-96a2-11ea-883c-006e69121cab.png)

I've try to pass the property Accept to Header as "application/json" or "**/**" but just works locally, when I run in production environment the return is "406 Not Acceptable".

Any suggestion?

**Comment by thinkingserious** [comment]
Hello @DHFerraz,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
