### ISSUE TITLE
Sendgrid Single Send email information in dashboard

### ISSUE THREAD

**Issue by rduman** [sendgrid/sendgrid-csharp#1007]
![image](https://user-images.githubusercontent.com/1703751/83500968-5d545600-a4b7-11ea-9e79-8f8487e13d01.png)

I use sendgrid  free account for testing. I send single send marketing email. But, sometimes it doesn't work. I don't know what's the error. There is not any information success or unsuccess.

Does any one have an idea?

**Comment by artursz1993** [comment]
I am unable to even send an email, using free account. I always receive StatusCode = Forbidden.
100% sure, that app is using newly generated API key.

**Comment by thinkingserious** [comment]
Hello @rduman,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
