### ISSUE TITLE
Error while making GET request to Email Activity Feed API through postman

### ISSUE THREAD

**Issue by rishabhvash26** [sendgrid/sendgrid-csharp#1020]
### Issue Summary
Even I have purchased the addon for extra storage then also when i am accessing Email Activity  data through API its showing authorization required error

### Steps to Reproduce
I am making a post request to https://api.sendgrid.com/v3/messages?limit=10&query=status%3D%22bounced%22

```

### Exception/Log
{
    "errors": [
        {
            "message": "authorization required"
        }
    ]
}

### Technical details:
* calling sendgrid Email Activity Feed API through Postman

**Comment by childish-sambino** [comment]
Are you passing your API key as bearer auth in Postman?

**Comment by rishabhvash26** [comment]
Yes. 
Instead of giving full access to API key when I am getting the scope of API key I am not able to get Email_activity.read permission.

**Comment by thinkingserious** [comment]
Hello @rishabhvash26,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
