### ISSUE TITLE
Format of exported contacts is invalid json

### ISSUE THREAD

**Issue by elenanakhmanson** [sendgrid/sendgrid-csharp#1024]
### Issue Summary
The files produced by marketing/contacts/exports/{export_job_id} endpoint have invalid json format. For example, exporting more than one contact produces this result:
{"contact_id":"b3c77877","created_at":"2020-06-19T10:05:25Z","custom_fields":{},"email":"mailbox@company.com","first_name":"Service","last_name":"Mailbox","updated_at":"2020-07-09T02:00:14Z"}
{"contact_id":"b53aa4b2","created_at":"2020-06-19T10:05:25Z","custom_fields":{"company_name":"Company LTD"},"email":"firstname@company.com","first_name":"SharePoint","last_name":"Administrator","updated_at":"2020-07-08T04:52:21Z"}
Notice that this is not an array and there's no comma between contacts, so parsing this json with JObject or JArray fails. 
Also attribute "id" of Contact object became "contact_id", which is different from other contact endpoints responses, why is that? 

### Steps to Reproduce
1. submit marketing/contacts/exports request with file_type = "json" to get the export_job_id
2. submit marketing/contacts/exports/{export_job_id} request
3. read the content of the produced file

### Technical details:
* sendgrid version: new Marketing Campaigns APIs

**Comment by thinkingserious** [comment]
Hello @elenanakhmanson,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
