### ISSUE TITLE
Changed signatures of SendGridClient is a breaking change

### ISSUE THREAD

**Issue by jenscski** [sendgrid/sendgrid-csharp#1027]
### Issue Summary
The changes in the constructors in https://github.com/sendgrid/sendgrid-csharp/commit/354215993b4a9c99a46e1b6d77a4b774afabd29b#diff-1b2f60fd3427373842af57c11d5a6e6e is a breaking change.

This will break other libraries bindings to this library, e.g. Microsoft.Azure.WebJobs.Extensions.SendGrid will not work with version 9.18.0

A new constructor, with the new variable has to be introduced instead, and revert the changes to the existing constructors.

### Technical details:
* sendgrid-csharp version: 9.18.0

**Comment by PunzunLtd** [comment]
Yes, this change broke all our code that depends on SendGrid. We had to roll back to 9.17.

**Comment by childish-sambino** [comment]
It's unclear to me why this is considered a breaking change. Optional boolean args were added to the end of the constructors as part of #1019, which should not be breaking. Are existing calls to the constructors resolving to a different constructor now?

**Comment by PunzunLtd** [comment]
The problem that our libraries encountered occurs at runtime, not at compile time. We have a NuGet package that has SendGrid >= 9.14.0 as a dependency. When a user of that library upgraded to SendGrid 9.18.0, they got this exception:

```
System.MissingMethodException : Method not found: 'Void SendGrid.SendGridClient..ctor(System.String, System.String, System.Collections.Generic.Dictionary`2<System.String,System.String>, System.String, System.String)'.
```

Adding a new, optional parameter to a method or constructor makes a runtime match impossible. Once you have deployed a specific public method signature, you can't change it. You can prevent this problem by creating an overload instead of a new optional parameter.

**Comment by childish-sambino** [comment]
TIL. Thanks for the explanation @PunzunLtd 

I'll work on a fix.
