### ISSUE TITLE
problemas con webhook

### ISSUE THREAD

**Issue by marcosss2018** [sendgrid/sendgrid-csharp#1034]
Hola,  necesito validar que un email fue entregado, voy a utilizar event webhook para esta tarea, cuando quiero testear con un endpoint ,  no recibo ningun evento.  que estoy haciendo mal?

No se envian test eventhook al ENDPOINT  que defino, 

<img width="511" alt="2020-08-11 11_48_59_TEST EVENT WEBHOOK" src="https://user-images.githubusercontent.com/35883105/89912512-065eb180-dbc9-11ea-9e59-0df62c42cac8.png">

saben como realizar esto? , event webhook  es la unica manera que hay para determinar si un mail fue enviado correctamente?

**Comment by thinkingserious** [comment]
Hello @marcosss2018,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Hola @marcosss2018, 

Gracias por enviarnos este tema de GitHub! Lamentamos que estes teniendo este problema. Para servirte mejor, ya que este tema no se presenta como un error de una librería especifica, nos gustaría pedirte que por favor te contactes con nuestro equipo de soporte en la pagina https://support.sendgrid.com. 

Gracias!

Equipo SendGrid DX
