### ISSUE TITLE
Gmail is clipping e-mails when body has any non-ASCII characteres

### ISSUE THREAD

**Issue by rgiosa** [sendgrid/sendgrid-csharp#1038]
Hello guys,

Gmail is clipping e-mails when body has any non-ASCII characteres, even when it's a small plain text e-mail.

**_Clipped e-mail_**
![image](https://user-images.githubusercontent.com/166394/90961075-aabfde00-e47c-11ea-92ef-b38f2436a8f7.png)

**_Without ASCII character_**
![image](https://user-images.githubusercontent.com/166394/90961174-67b23a80-e47d-11ea-8079-c2e6490924c9.png)
Is there any way to prevent this behaviour?

I'm using ASP.NET Core 3.1 and latest Sendgrid Nuget package.

```csharp
var client = new SendGridClient(API_KEY);

var msg = new SendGridMessage()
{
	From = new EmailAddress(fromEmail, fromName),
	Subject = subject,
	PlainTextContent = body,
};

foreach (var item in to)
	msg.AddTo(new EmailAddress(item));

await client.SendEmailAsync(msg);
```

Thanks!

**Comment by thinkingserious** [comment]
Hello @rgiosa,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
