### ISSUE TITLE
Messages missing a valid address in From: header, or having no From: header, are not accepted.

### ISSUE THREAD

**Issue by babloo-singh** [sendgrid/sendgrid-csharp#1039]
### Issue Summary
We are facing the issue of message bouncing when sent to SendGrid, this is mostly affecting the gmail mail addresses. Everything was working fine till 08/25 but then the mails started to bounce. We now have a mail bounce of ~20%. This is a serious business impact and support from SendGrid isn't helping. A mail with same contents and receiver passed while the second time it failed. 

Nothing changed on how we use your service and when setting the from address we use MailAddress (string address, string displayName).

### Exception/Log

550 5.7.1 [167.89.67.183 14] Messages missing a valid address in From: header, or having no From: header, are not accepted. f5si72061edr.222 - gsmtp

**Comment by thinkingserious** [comment]
Hello @babloo-singh,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
