### ISSUE TITLE
GET template method sometimes returns 406

### ISSUE THREAD

**Issue by gastonmuijtjens** [sendgrid/sendgrid-csharp#1041]
### Issue Summary
I have a service running in Azure which daily calls the `GET templates` (https://sendgrid.com/docs/API_Reference/Web_API_v3/Transactional_Templates/templates.html#-GET) endpoint for the same template id using this C# Nuget package (see code example below). Approximately 20-40% of the calls for exactly the same template id fail due to SendGrid returning a 406. Most of the times the calls work just fine though, it is very unpredictable.

This might be an issue on the SendGrid server side, rather than a specific issue for this Nuget Package.

### Steps to Reproduce
I am not able to reproduce this issue locally. It happens at some moments within Azure.
1. Call the `GET templates` endpoint with an existing template id

### Code Snippet
The following code runs for the same template id (which I'm sure exists within the template manager in SendGrid).
```csharp
private readonly ISendGridClient _client;

private async Task CheckTemplateByIdAsync(string templateId)
{
    var templateResponse = await _client.RequestAsync(BaseClient.Method.GET, urlPath: $"/templates/{templateId}");
    if (templateResponse.StatusCode != HttpStatusCode.OK)
    {
        // ...
    }
}
```

Dependency injection configuration:
```csharp
 public static void ConfigureServices(IServiceCollection serviceCollection)
 {
       serviceCollection.AddSendGrid(opt =>
       {
           opt.ApiKey = _configuration["SendGridApiKey"];
       });
 }
```

### Exception/Log
SendGrid gives a 406 response.

### Technical details:
* sendgrid-csharp version: 9.18.0

**Comment by JayDZimmerman** [comment]
We were seeing this yesterday:  one of our four environments in Azure was getting the 406 errors.  Working fine all morning, majority errored during the afternoon, and then cleared back up sometime last night/this morning.  I am guessing the problem was not with the API package but rather something on the SendGrid server side.  Hopefully it is an anomaly and doesn't resurface.

**Comment by thinkingserious** [comment]
Hello @gastonmuijtjens,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by hhermas** [comment]
This is not fixed. We are still encountering 406 Not Acceptable errors on GET templates. 
At least 5 failures with the same message across almost an hour seems like not really transient.

Response body:
```
<html>
<head><title>406 Not Acceptable</title></head>
<body bgcolor="white">
<center><h1>406 Not Acceptable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Here is a similar issue reported for the Python version of SendGrid's library back in 2015, which was fixed by patching the library itself:
https://github.com/sendgrid/sendgrid-python/issues/149

**Comment by childish-sambino** [comment]
@hhermas I don't see any patches to fix the problem in python and users still reported issue after the mentioned release. This is something that requires assistance from support as linked above.
