### ISSUE TITLE
SendGrid  giving a status of 200(OK)  instead of 202(Accepted) on Azure VM

### ISSUE THREAD

**Issue by ashutoshbhadoria** [sendgrid/sendgrid-csharp#1043]
When I run my code on an on-premise windows server VM I get the correct status 202 and my emails are sent.
However, on my Azure VM when I run the same code I get the status 200 and the emails are not sent.

```
SendGridAPIClient sendGridAPIClient = new SendGridAPIClient(this.apiKey, this.hostBaseUrl, this.webApiVersion);
// a utility method to convert .Net MailMessage to SendGridMessage
Mail sendGridMail = this.GetSendGridMail(mailMessage);
SendGrid.CSharp.HTTP.Client.Response response = sendGridAPIClient.client.mail.send.post(requestBody: sendGridMail.Get());
```

What am I doing wrong?

**Comment by thinkingserious** [comment]
Hello @ashutoshbhadoria,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by ashutoshbhadoria** [comment]
Thanks for the response. Apologies for this, it turned out to be a cloud firewall issue. This can be closed
