### ISSUE TITLE
Unsupported Media Type .NET Core 3.1

### ISSUE THREAD

**Issue by Dmo16** [sendgrid/sendgrid-csharp#1044]
### Issue Summary
When using the integration guide from SendGrid's website, I am unable to send emails and receive an "Unsupported Media Type" response from Sendgrid.

### Steps to Reproduce
1. Copy code from integration guide
2. Minor modifications for project
3. Trigger email sending from Blazor form
4. Error in result

### Code Snippet
```csharp
    public class EmailSender
    {
        private readonly IConfiguration _configuration;
      
        public EmailSender(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task SendEmail(NewProjectContact contactForm)
        {
            try
            {
                //Email Settings
                
                var apiKey = _configuration.GetSection("SendGrid")["ApiKey"];
                var senderEmail = _configuration.GetSection("SendGrid")["SenderEmail"];
                var client = new SendGridClient(apiKey);
                var from = new EmailAddress(contactForm.Email, contactForm.FirstName + contactForm.LastName);
                var subject = $"New Project Request from {contactForm.FirstName + contactForm.LastName}";
                var to = new EmailAddress("hello@lowlineracing.com", "Design Services");
                var plainTextContent = $"{contactForm.Message}";
                var htmlContent = $"{contactForm.Message}";
                var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
                var response = await client.SendEmailAsync(msg);

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
        }
    }
```

### Exception/Log
```
None
```

### Technical details:
* sendgrid-csharp version: 9.21.0
* csharp version: Latest

**Comment by eshanholtz** [comment]
@Dmo16 

Please see our [troubleshooting guide on how to read error messages from responses](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#error-messages) as well as our [guide on viewing your request body](https://github.com/sendgrid/sendgrid-csharp/blob/main/TROUBLESHOOTING.md#viewing-the-request-body), and include the contents of both in a comment so we can further help you.

**Comment by Hechamon** [comment]
Hi there
We are having the same problem, when running our app in a Linux container on Kubernetes, when running it from my Windows development computer it works fine.
The Request body is fine, we called the serialize method and sent the json from local without the media type error. I cannot post it thou because of privacy concerns.

The response code is 415, the body `{"errors":[{"message":"Content-Type should be application/json.","field":null,"help":null}]}`
We tried setting the media type in the client manually, without success.
The headers are the following:
`Server: nginx
Date: Fri, 02 Oct 2020 16:58:57 GMT
Connection: keep-alive
Access-Control-Allow-Origin: https://sendgrid.api-docs.io
Access-Control-Allow-Methods: POST
Access-Control-Allow-Headers: Authorization, Content-Type, On-behalf-of, x-sg-elas-acl
Access-Control-Max-Age: 600
X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html`

Do you have any ideas on what we could try next?

**Comment by childish-sambino** [comment]
Best to leverage SendGrid Support to help debug this issue to see why the content type is not being accepted.

**Comment by thinkingserious** [comment]
Hello @Dmo16,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
