### ISSUE TITLE
Emails getting Deferred

### ISSUE THREAD

**Issue by ysunil702** [sendgrid/sendgrid-csharp#1048]
### Issue Summary
We were on a free plan that we got from the Microsoft Azure. We saw that from 10 sept the mails were not getting delivered (deferred).  The error showed that the Sendgrid IP was blocked. 

We thought that the reason being that we were on shared IP. So we upgraded the  plan so to have a dedicated IP. (Sendgrid Pro plan, In Azure it is named as Silver plan)

The emails started getting delivered but after some time the emails again started getting deferred. This time the error being that the IP was new or unauthorized. I think the IP was not warmed. 

Can you please suggest the way forward. 

### Technical details:
* sendgrid-csharp version: 
* csharp version:

**Comment by shyambabu-kolipaka** [comment]
Hi, We are facing the same issue. We upgraded the plan to Silver on Azure. But still mails are getting deferred.

**Comment by thinkingserious** [comment]
Hello @ysunil702,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
