### ISSUE TITLE
Didn't receive Spam Report on Event Webhook after reporting as spam in Gmail

### ISSUE THREAD

**Issue by mars-boy** [sendgrid/sendgrid-csharp#1073]
### Issue Summary
I have sent a mail from authenticated domain to a test account in gmail I clicked on spam it's been a while as I didnt receive any notification on web hook. Able to get events like open/click alerts 

### Steps to Reproduce
1. Configure Event Webhook make sure able to receive notifications
2. Send a mail to some valid Gmail account
3. Click on Spam

### Technical details:
* sendgrid-csharp version: 9.21.2
* csharp version: Dotnet core 3.1

**Comment by thinkingserious** [comment]
Hello @mars-boy,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
