### ISSUE TITLE
Generating a unique bar code for email inclusion

### ISSUE THREAD

**Issue by Fuji183** [sendgrid/sendgrid-csharp#1078]
Hi,

There was an old post asking whether there was a method of incorporating a unique bar code within the body of an email but there was no solution at the time.  So, I just wanted to ask if anyone out there in the community has come across a suitable solution for generating a unique bar code (to be used for reference / tracking purposes during any scanning acticity) to be included in the body of an email sent via SendGrid?

TIA

**Comment by thinkingserious** [comment]
Hello @Fuji183,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
