### ISSUE TITLE
Retry on HTTPclient error/exception

### ISSUE THREAD

**Issue by chris-hockeystickco** [sendgrid/sendgrid-csharp#1079]
Question:
Does the latest stable version implement the subject line internally? I see discussion of embedding Polly which was later removed (in 9.5.2). Has this feature been re-implemented? If not, is there a recipe for a Polly implementation?

**Comment by JenniferMah** [comment]
Hi @chris-hockeystickco
You should be able to customize the subject line as seen in the examples [here](https://github.com/sendgrid/sendgrid-csharp/blob/main/USE_CASES.md). The original intent behind using Polly was for transient fault handling, which was achieved by this [PR](https://github.com/sendgrid/sendgrid-csharp/pull/497). The dependency was removed because the functionality it originally offered could be [achieved without the dependency](https://github.com/sendgrid/sendgrid-csharp/issues/501). We do not currently have any plans internally for a Polly implementation.
