### ISSUE TITLE
EmbedImage does not work without using AttachImage

### ISSUE THREAD

**Issue by twilly86** [sendgrid/sendgrid-csharp#108]
You should be able to embed an image without also attaching the image to an email.  I'm getting some weird effects from having to also attach the image such as the email stating it has attachments, when really they are just embedded images.

Sample code can be found here...
http://stackoverflow.com/questions/27328223/sendgrid-smtp-api-embed-image-bad-request

**Comment by brandonmwest** [comment]
Whether or not embedded content shows up as an attachment is determined by the client, not by the MIME message. Embedded images are by definition attachments. If you don't want the attachment, then link the image rather than making embedding it. Let me know if have questions! :)

**Comment by mattwoberts** [comment]
I had this to, and have had support tickets back and forth with sendgrid on this.

Unless something has changed, this is not FIXED. The issue is thus:

If you use the standard c# SMTP client, and embed an image, it always works as expected in all mail clients.

If you use the sendgrid API, to embed the images, then, as the original SO question states, you HAVE to include the image as an attachment to make it work. Doing this makes the resulting email work in some clients, but not all - for example the android gmail app shows the images at the bottom of the email.

Here's a response from a sendgrid support engineer confirning this is an issue:

----

I found both of the emails that you sent - The emails seem to render correctly without any attachments at the bottom in both my browser and on my iPhone but I was able to replicate this when opening the message in Apple Mail and Outlook. With that being said, I took a look at the source for both emails - The messages that have the images showing as attachments have boundary delineating sections containing a Content-Disposition and X-Attachment-Id part which I believe is what's causing this and are a side effect of having to add the image as an attachment prior to embedding.

I brought this up with our dev team that maintains this repo and they pointed me to the issues section of the c-sharp library - This appears to be a known issue that is being worked on. If you could add any relevant notes to this open issue then I can also alert the team on my end so that we can get this worked on a bit quicker.

Email showing as attachments as well:

--===============4894311612584497259==
Content-Type: image/png
MIME-Version: 1.0
Content-Transfer-Encoding: base64
Content-ID: <email_logo>
Content-Disposition: inline; filename="email_logo.png"
X-Attachment-Id: email_logo
I apologize for the delayed response and thanks for reporting this to us as we are constantly looking to provide the best experience possible to our community.

Let me know if there's anything else that I can help with!

**Comment by brandonmwest** [comment]
Can you post the code you are using to send the message?

**Comment by mattwoberts** [comment]
Here is the code I am using. The mail I am sending is already contained in a .NET mail object, so I'm reading from that and putting it into a sendgrid mail object and sending via the API (I do this because I Want to use additional API functionality like including unique tracking codes)

    var sendGridMail = new SendGridMessage();

    // Set the From, To, Subject, etc.. (omitted)

    // Set the content
    sendGridMail.Html = mail.GetHtmlString();
    sendGridMail.Text = mail.GetPlainTextString();

    // Add the embedded images.. they are currently stored in a .net mail "AlternateView", so we iterate that:
    foreach (LinkedResource linkedResource in htmlView.LinkedResources)
    {
        string fileName = linkedResource.ContentId + ".png"; // Will be e.g. logo.png
        sendGridMail.AddAttachment(linkedResource.ContentStream, fileName); // Include the attachment from the content stream (won't work without doing this)
        sendGridMail.EmbedImage(fileName, linkedResource.ContentId); // Embed the image too
    }

    // Add some unique args for tracking (omitted)

    // Now send it
    var credentials = new NetworkCredential {UserName = CloudConfigurationManager.GetSetting("SendGridUsername"), Password = CloudConfigurationManager.GetSetting("SendGridPassword")};
    var transport = new SendGrid.Web(credentials);

**Comment by mattwoberts** [comment]
Hi
Any update on this?
