### ISSUE TITLE
Embedded API Keys

### ISSUE THREAD

**Issue by jamsoft** [sendgrid/sendgrid-csharp#1086]
Sorry this is a question but I was unsure where else to ask.

I'm planning on using send grid to send crash reports from a desktop app to my support email address.

The only API key examples load the key from Environment variables. Whereas I would need to embed an API key in my compiled app.

The app is encrypted and obfuscated so I'm not too concerned about it being easily discoverable but was wondering if there were any best practice guidelines from Twilio on this?

**Comment by thinkingserious** [comment]
Hello @jamsoft,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
