### ISSUE TITLE
Using dynamic templates for sending newsletters via API v3 

### ISSUE THREAD

**Issue by OlehTymoshenko** [sendgrid/sendgrid-csharp#1089]
### Issue Summary
I want to send a newsletter to multiple recipients. I created dynamic template for this. I pass a data for a template via "dynamic_template_data" field in a JSON. Almost all data is same for each recipient, but i have one field that should be personalized(unique) for each recipient. Can I create a shared "dynamic_template_data" field in a one level higher, than "personalizations" and then pass in "personalizations":"dynamic_template_data" only one personalized field for each recipient? In this case JSON should be like this 
![image](https://user-images.githubusercontent.com/40433027/107060011-27523900-67df-11eb-822e-78cb0cd0b90f.png).

I assume this is incorrect way to using SendGrid API now, so how i can reach my purpose?  
I would appreciate any help.

P.S. I know it's possible pass all data in dynamic_template_data field for each object in "personalizations" array, but in this case HTTP request body size will be very big. In this case JSON should be like this.
![image](https://user-images.githubusercontent.com/40433027/107061181-86647d80-67e0-11eb-8bfa-e13d4f964034.png)

### Technical details:
* sendgrid-csharp version: 9.21.2

**Comment by thinkingserious** [comment]
Hello @OlehTymoshenko,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
