### ISSUE TITLE
Locked out of my account due to IP address whitelisting

### ISSUE THREAD

**Issue by JohnnyQQQ** [sendgrid/sendgrid-csharp#1092]
### Issue Summary
Locked out of my account, I'm the only user

### Steps to Reproduce
I try to login and and it's telling me I'm not allowed because of white listing

I get emails telling me I tried to login in by using a non-whitelisted account.

https://content.screencast.com/users/Ekriuq/folders/Snagit/media/e69be860-97be-468a-9e72-217a7b571311/02.27.2021-19.25.jpg

Resetting the password does nothing

**Comment by thinkingserious** [comment]
Hello @JohnnyQQQ,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
