### ISSUE TITLE
SendGrid ApiKey Implementation in classic asp page

### ISSUE THREAD

**Issue by rukish** [sendgrid/sendgrid-csharp#1103]
Could anyone help me to implement send grid apikey implementation in a classic ASP page?

**Comment by thinkingserious** [comment]
Hello @rukish,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
