### ISSUE TITLE
Not able to send email to group alias

### ISSUE THREAD

**Issue by yadavsachin** [sendgrid/sendgrid-csharp#1107]
I am using below version of send grid. I want to send email to group alias. I am getting OK response but email is not getting sent
Assembly SendGrid, Version=9.8.0.0

**Comment by thinkingserious** [comment]
Hello @yadavsachin,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
