### ISSUE TITLE
Exception Handling for SendGrid Emails

### ISSUE THREAD

**Issue by ravvenukam** [sendgrid/sendgrid-csharp#116]
Hi,
We are using SendGrid C# Library for sending transaction emails. Emails are not getting delivered sometimes but we see emails delivered to the same email id sometimes before or after when we try in different time but we are missing some emails.
transportWeb.Deliver(myMessage); is not throwing any exception but emails are not getting delivered to recipient.
When we contact tech support of sendgrid ,they are saying they didn't even receive email requests in such scenario. How can we know whether the email request has been sent to sendgrid successfully or not if the above method is not returning any exception and emails are not delivered.

**Comment by ravvenukam** [comment]
Its been 20 days we have reported the issue..no resolution yet....

**Comment by MarcelloCarreira** [comment]
Hello, I also believe that transportWeb should return some information from the server when it successfully has delivered the message to the api. I know this is not the same as knowing if the message itself was delivered to the recipient (this is done using the Webhooks). But this information is indeed very useful, because you can retry sending the message to the api if you got an error. For example, I sometimes try to deliver a message, but I got an invalid api key, but the key is untouchable and also the code, the error is at the transport or at the api itself. So having an OK back message is crucial to have some peace. I forked the this C# rep, to have transportWeb.DeliverAsyncReturn() but I would love to see it in the official one.

**Comment by brianptx** [comment]
I agree.  We need more detailed status information returned from the DeilverAsync method with the actual result of the call (similar to calling mail.send.json directly via http post) with "success" or "error" along with the detailed message if an error exists. I don't see how to get this info when calling transportWeb.DeliverAsync.

**Comment by Wirwing** [comment]
Any status on this? I'm planning to integrate SengGrid in one big eCommerce application and this is a feature killer the customer wants.

Maybe I should try Mandrill (MailChimp) instead...

**Comment by thinkingserious** [comment]
This is a related pull request, just putting it here for later reference: https://github.com/sendgrid/sendgrid-csharp/pull/135

**Comment by thinkingserious** [comment]
This is on our roadmap, see pull request #135
