### ISSUE TITLE
How to save emails in a temp folder when in development mode.

### ISSUE THREAD

**Issue by wpalombini** [sendgrid/sendgrid-csharp#138]
Hi everyone,

With the classic SmtpClient, instead of sending the email out, we can save it on the c drive in a folder.
How can I achieve this with this sendgrid library?
This is very useful when running tests in development mode.

Thanks

**Comment by brandonmwest** [comment]
You'll need to implement some kind of logging, but you won't be able to see the actual message, because the MIME message itself is built by SendGrid based on the HTTP request, not by this library. So  the best you'll be able to do is inspect the object. To view the actual message you'll need to send it somewhere where you can view the raw message content.
