### ISSUE TITLE
Possible to re-introduce a proper synchronous API?

### ISSUE THREAD

**Issue by DavidR91** [sendgrid/sendgrid-csharp#142]
Perhaps I'm in the minority, but asynchrony is actually really *un*helpful for my particular use of Sendgrid.

I specifically **want** to wait for the POST to finish so that I can mark the work as successful/unsuccessful at the point when it is processed. Deferring results until an unknown point in the future makes determining success/failure significantly harder 

Is there any chance of introducing a better synchronous API? Or perhaps splitting the library in two for focusing on synchrony vs. asynchrony?

Failing these, is there some way we can at least have better result tracking of asynchronously sent messages? (e.g. a token for tracking their state rather than just receiving errors at unknown points in the future)

**Comment by DavidR91** [comment]
OK: Apologies, I missed the SendGrid.Net40 fork mentioned in the README

Is it possible to shout out to this fork slightly more prominently in the docs? (now that new projects will be receiving this current version via nuget, it would be appreciated if you could say something to the effect of 'Can't use async? Go here')

**Comment by smurfpandey** [comment]
I was about to update that fork, and remove the synchronus API becuase of https://github.com/sendgrid/sendgrid-csharp/issues/103. But I guess i will have to keep the synchronous method.

Any chance you can use Sendgrid Events webhook mentioned in the [docs](https://sendgrid.com/docs/API_Reference/Webhooks/event.html)

**Comment by smurfpandey** [comment]
Or maybe this pull request will help you https://github.com/sendgrid/sendgrid-csharp/pull/135

**Comment by brandonmwest** [comment]
The thing is that HttpClient is all async, so if you make a "synchronous" method you're just mixing sync and async code. You're welcome to wrap the method in something that awaits it to simulate the async method yourself (which is what this library used to do, so looking at the code history will show how), but mixing sync and async is generally not advisable. For tracking async messages and error states, that's really dependent on the code you write to handle the async tasks and not a concern of the async call itself.

Also keep in mind that theSendGrid API calls themselves are async, because we accept the message before verifying that it can be successfully processed and sent.
