### ISSUE TITLE
I cannot get my messages to track Opened Tracking

### ISSUE THREAD

**Issue by NashCarr** [sendgrid/sendgrid-csharp#152]
When I send my test email I get a web hook back for processed and delivered but not opened.
I am using the EnableOpenedTracking example.

           message.EnableOpenTracking();

**Comment by NashCarr** [comment]
I do see this within the message:  ((SendGrid.SmtpApi.Header)myMessage.Header).To' threw an exception of type 'System.ArgumentException  

but can't determine what is causing this.

**Comment by NashCarr** [comment]
I will add that the Track Clicked option also works but not the opened.

**Comment by thinkingserious** [comment]
Hello @NashCarr,

Thanks for submitting your issue!

Here is an example of how you can review the exception message: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Program.cs#L40

We have implemented a new v3 /mail/send endpoint which now handles click tracking directly instead of in the SMTPAPI header. You can check it out here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Also, this library will be replaced with this branch, which supports the v3 /mail/send endpoint: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

Here is an example of the setting in the new library: https://github.com/sendgrid/sendgrid-csharp/blob/v3beta/SendGrid/Example/Example.cs#L207

If you continue to experience issues using the new library, please feel free to reopen this ticket.

With Best Regards,

Elmer
