### ISSUE TITLE
Please provide more complete example

### ISSUE THREAD

**Issue by pkellner** [sendgrid/sendgrid-csharp#172]
Please add to the example the following two things:  1) include smtpapi value like I do by adding header record for custom values to be tracked by webhooks   2) show how to send more then one email at a time (per request)

**Comment by thinkingserious** [comment]
Hello @pkellner,

Thank you for your feedback!

The new version of the v3 /mail/send endpoint no longer requires SMTPAPI headers, you can check it out here: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

Also, this library is being replaced with this one: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

I will close this issue, since this library will be replaced within a few weeks.

With Best Regards,

elmer
