### ISSUE TITLE
Attachments aren't send if file name contains hyphen

### ISSUE THREAD

**Issue by proleskovskiy** [sendgrid/sendgrid-csharp#178]
Hello.

This is a quite tricky issue - it was way to difficult to guess that FILENAME is a problem. But anyway - I get no error, nothing tells me that I'm doing something wrong - I receive letter as usual but without attachment. In case I have a filename without hyphen - I get both. Tried with '*.pdf' attachment.

**Comment by polarbit** [comment]
I have the same problem.

**Comment by alejandrobog** [comment]
I have the same problem, in my case I get no exception and the request is never made. How are we suppose to know the call failed?

**Comment by thinkingserious** [comment]
Hello @proleskovskiy @polarbit, @alejandrobog ,

We are replacing this library: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta with a new one which rely's on a new v3 /mail/send API: https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html

I'm not sure if the updates fix the issue, but if they don't then it's likely an API issue. In that case, please open a ticket at https://support.sendgrid.com.

I'm leaving this open until we have time to test through the new library.

Thanks for your support!

With Best Regards,

Elmer

**Comment by alejandrobog** [comment]
Thanks,

It was an issue with the library, when the attachment name contained an
special character in my case a pipe I got no exception even though the
request failed. I ended up downloading the source code and modifying
otherwise it was impossible to know when something went wrong

Saludos,

*Alejandro Bonilla*

Minnt Solutions S.A. de C.V.
T: (81) 18772867 ext 301
www.bind.com.mx

El presente mensaje es confidencial, dirigido únicamente para el
destinatario. Si usted no es el destinatario, no deberá copiarlo, revelarlo
o distribuirlo. Cualquier acción realizada en este sentido, será ilegal. Si
por error recibe el presente mensaje, por favor notifique al remitente.

This communication is confidential and intended only for the addressee. If
you are not the intended recipient, you may not copy, disclose, or
distribute this message to anyone else; any such actions may be unlawful.
If you have received this communication in error, please contact the sender
of the message to inform him or her of the error.

**Comment by thinkingserious** [comment]
@alejandrobog,

Thanks for the update!

Do you mind sharing your solution with us? Or providing a pull request?
