### ISSUE TITLE
Need to specify message Text or Html, if using Template Engine ?

### ISSUE THREAD

**Issue by andronachev** [sendgrid/sendgrid-csharp#228]
Hi,

We are planning on using message templates, designed using SendGrid Dashboard. And so, from our application we only need to send a template ID, subject and a list of substitutions for the template. 

However, I see that the message is not being sent, unless I also specify the Text and/or HTML property of the SendGridMessage object, which gets replaced at the <%body%> tag. So the question is: 

is there any way around this ? Beacuse in our case, the whole template IS the "<%body%>". Only way I could figure around this, is to send an empty string in the Text property, but it's not elegant. 

Thanks for your response @thinkingserious

**Comment by andronachev** [comment]
I found a duplicate of this, described in this issue: 

https://github.com/sendgrid/sendgrid-csharp/issues/157

Then my question is, when will this fix be available in the nuget package, of the this library ? Thanks!

**Comment by thinkingserious** [comment]
Hello @andronachev,

This version of the library will not be updated with a fix for that issue; however, the new version of this library is just about ready to come out of beta, you can check it out here: https://github.com/sendgrid/sendgrid-csharp/tree/v3beta

That issue should no longer be an issue, since we have fixed it at the API layer. If you continue to have issues, please feel free to open a new ticket with respect to the new library.

Thank you!

With Best Regards,

Elmer
