### ISSUE TITLE
Update README and Code to explain the Environment Variable setup

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#243]
#### Issue Summary

This explanation should be in the README and as a comment in the example code:
https://github.com/sendgrid/sendgrid-csharp/blob/master/CONTRIBUTING.md#environment-variables

Also, show an example of retrieving the API Key from `web.config`
#### Technical details:
- sendgrid-csharp Version: 7.0.2
- .NET Version: 4.5.2

**Comment by J242** [comment]
Hello, can you show us how to set up the send grid key? See support question below:

kosullivan Wednesday at 13:19
Hello, I'm setting up SendGrid with C# in Visual Studio Express 2013 for Web with the Quickstart located at https://github.com/sendgrid/sendgrid-csharp and testing on my local machine. Once I get it working, I will deploy to Azure. I have set up an account, set up a key, and installed SendGrid and its dependencies from the NuGet package manager, and set up a web page that runs the Quick Start's code. In the Installation>Setup Environment Variables section it reads, "Next, update your Environment (user space) with your SENDGRID_API_KEY." Where (what file) and how is this done? Where in my project do I store the key?

Avatar
Ryan R. Friday at 14:00
 
Hi there,

 
Please feel free to contribute to this Github issue in order to get an answer from our developers.

 
Best,
 Ryan R.

**Comment by thinkingserious** [comment]
Hello @J242,

You will want to setup your environment variables in Azure. Here is some help on how to do that: 

https://blogs.msdn.microsoft.com/stuartleeks/2015/08/10/azure-api-apps-configuration-with-environment-variables

http://stackoverflow.com/questions/34608769/how-and-where-to-define-an-environment-variable-on-azure

Please let me know what resource was most helpful to you. 

Thanks!

**Comment by aaron-horst** [comment]
You are not required to use environment variables correct? The raw string can still be passed in if it lives as a setting in your app.

**Comment by andredublin** [comment]
@aaron-horst that is correct, for example I store the api key in a cloud configuration file and reference it from there with the CloudConfigurationManager

**Comment by J242** [comment]
Thanks for the info everyone! 

Can I store the api key in my asp.net project's web.config so that I can test it on my local computer before deploying the tested solution to Azure?

**Comment by andredublin** [comment]
@J242 Yes, so long as your able to retrieve the string it can be stored anywhere really.

**Comment by J242** [comment]
Cool! I'll probably try both methods. I'll use web.config locally and environment on Azure.

**Comment by thinkingserious** [comment]
Please see https://github.com/sendgrid/sendgrid-csharp/issues/473#issuecomment-308615551
