### ISSUE TITLE
Two Questions: subject line and multiple recipients

### ISSUE THREAD

**Issue by J242** [sendgrid/sendgrid-csharp#264]
#### Issue Summary

Hello,
We've got our send grid set up and working with the c sharp api so that's great.
We have two questions:

1) Why can't we seem to get the subject line of our message to be anything other than "Hello World form the send grid c sharp library"?

2) How do we alter this code to send to multiple recipients? The documentation makes a vauge suggestion that you need to include a json array, but we can't seem to force the  

Mail mail = new Mail(from, subj, to, content); 

method to accept an array.

Thanks!!!

Here is all of the code of the contactUs.aspx.cs code behind file:

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using SendGrid;
using System.Web.Script.Serialization;
using SendGrid.Helpers.Mail;
using System.Text;

public partial class _2014_ContactUs : System.Web.UI.Page
{

    protected void FormView1_ItemInserting(object sender, FormViewInsertEventArgs e)
    {

        String apiKey = "XXXX";

        dynamic sg = new SendGrid.SendGridAPIClient(apiKey);

        Email from = new Email("info@test.com");
        String subj = "Website Contact Us Form Submission";
        Email to = new Email("me@test.com");

        StringBuilder sb = new StringBuilder();
        sb.Append("The following info was submitted:<p>");
        sb.Append("<b>first name: </b>" + e.Values["FName"].ToString() + "<br/>");
        sb.Append("<b>last name: </b>" + e.Values["LName"].ToString() + "<br/>");
        sb.Append("<b>email: </b>" + e.Values["Email"].ToString() + "<br/>");
        sb.Append("<b>subject: </b>" + e.Values["Subject"].ToString() + "<br/>");
        sb.Append("<b>message: </b>" + e.Values["Message"].ToString() + "<br/>");

        string bodyOfEmail = sb.ToString();

        SendGrid.Helpers.Mail.Content content = new SendGrid.Helpers.Mail.Content("text/html", bodyOfEmail);

        Mail mail = new Mail(from, subj, to, content);

        dynamic response = sg.client.mail.send.post(requestBody: mail.Get());

        Label_Confirmation.Text = "Message Sent.";
    }
}

**Comment by thinkingserious** [comment]
Hello @J242,

1) Please update to version 7.0.4. That bug was fixed in version 7.0.1

2) The code you are using for sending an email is a demonstration of a simple case of sending to a single email. For sending to multiple recipients you will want to use personalizations. Here is an example: https://github.com/sendgrid/sendgrid-csharp/blob/master/SendGrid/Example/Example.cs#L47

Also, you may want to check out this documentation for a deeper understanding about our v3 /mail/send endpoint:
https://sendgrid.com/docs/API_Reference/Web_API_v3/Mail/index.html
https://sendgrid.com/docs/Classroom/Send/v3_Mail_Send/index.html

Thanks!
