### ISSUE TITLE
I have problem

### ISSUE THREAD

**Issue by OmerKorkmaz** [sendgrid/sendgrid-csharp#269]
Hi everyone.

I have problem. I am using .NET framework 4.5 and I installed SendGrid below link. But I get error
 using SendGrid.Helpers.Mail; here. this refences doesnt exist. How can I do.

https://github.com/sendgrid/sendgrid-csharp

**Comment by Jimwaga** [comment]
Did you add ‎the references under the project/solution                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: OmerKorkmazSent: Tuesday, 12 July 2016 05:49To: sendgrid/sendgrid-csharpReply To: sendgrid/sendgrid-csharpSubject: [sendgrid/sendgrid-csharp] I have problem (#269)Hi everyone.

I have problem. I am using .NET framework 4.5 and I installed SendGrid below link. But I get error
 using SendGrid.Helpers.Mail; here. this refences doesnt exist. How can I do.

https://github.com/sendgrid/sendgrid-csharp

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by paritoshmmmec** [comment]
@OmerKorkmaz : FYI this project has been upgraded to 4.5.2 framework and will not compile against older versions. 

please give us more details

**Comment by thinkingserious** [comment]
Thanks @Jimwaga and @paritoshmmmec for jumping in to help :)

@OmerKorkmaz,

Can you upgrade your project to support 4.5.2? If not, you can try downloading this source code and compiling it yourself. This has worked for others who needed support on 4.5.
