### ISSUE TITLE
The type or namespace name Helpers does not exist in the namespace SendGrid (are you missing an assembly reference?)

### ISSUE THREAD

**Issue by muze-net** [sendgrid/sendgrid-csharp#271]
Hi,
i'm working in .Net 4.5,Visual Studio 2013.
i've installed SendGrid (v7.0.6.0) from nuget and copied the code from the samples page.
everything look OK ,but when i'm trying to build i'm getting an error:
"The type or namespace name Helpers does not exist in the namespace SendGrid (are you missing an assembly reference?)".
i've looked around the web, but haven't been able to locate a fix yet.
any help will be greatly appreciated !

Thanks!

**Comment by thinkingserious** [comment]
@muze-net,

Thanks for reaching out to us!

Version 7.0.6.0 targets .Net 4.5.2. If you want to use v7.0.6.0 in your project, you would need to recompile the source code to target .Net 4.5. Alternatively, you could update your project to target .NET 4.5.2.

We do not support .Net 4.5 or 4.5.1 because Microsoft no longer supports those.
