### ISSUE TITLE
"Cannot invoke a non-delegate type" error when using underscore method

### ISSUE THREAD

**Issue by RaceProUK** [sendgrid/sendgrid-csharp#322]
When calling `sg.client.contactdb.lists._(listId)`, I'm getting an exception with the message "Cannot invoke a non-delegate type".
I'm using the same syntax as shown int he example code (https://github.com/sendgrid/sendgrid-csharp/blob/master/examples/contactdb/contactdb.cs).

How can I resolve this error?

* sendgrid-csharp Version: 8.0.4
* .NET Version: 4.6.1

I'm able to use other parts of the SendGrid library without issue with .NET 4.6.1; it's only the underscore method that's not working.

**Comment by RaceProUK** [comment]
Solved the problem: turns out `listId` has to be a string, something that is missing from the documentation, not shown through IntelliSense because of everything being `dynamic`, and also seemingly unrelated to the exception thrown.

**Comment by thinkingserious** [comment]
Hey @RaceProUK,

Thanks for letting us know how you solved it. That issue should be fixed with this is complete: https://github.com/sendgrid/sendgrid-csharp/issues/303. If you have not already, I'd appreciate if you gave a plus 1 to that thread to help bump it's priority.

Also, pleas shoot us an email at dx@sendgrid.com with your mailing address and T-shirt size :)
