### ISSUE TITLE
'SendGrid.CSharp.HTTP.Client.Client' does not contain a definition for 'mail'

### ISSUE THREAD

**Issue by ashkansiroos** [sendgrid/sendgrid-csharp#372]
#### Issue Summary
I am trying to send emails using code below and it works most of the times, but sometimes it comes back with this error:
Exception thrown: 'Microsoft.CSharp.RuntimeBinder.RuntimeBinderException' in Microsoft.CSharp.dll
Additional information: 'SendGrid.CSharp.HTTP.Client.Client' does not contain a definition for 'mail'

**I am using .net 4.6.1 and Sendgrid 8.0.5 with targetFramework="net451"**

     public async Task SendCreationEmail(string toEmail, MyModel model)
        {
            dynamic sg = new SendGridAPIClient(SettingsHelper.Instance.EmailApiKey, "https://api.sendgrid.com");

            Email from = new Email(SettingsHelper.Instance.Sender);
            Email to = new Email(toEmail);
            Content content = new Content("text/html", "content");
            Mail mailSt = new Mail(from, "subject", to, content) { TemplateId = SettingsHelper.Instance.CreationTemplateId };

            mailSt.Personalization[0].AddSubstitution("@@GatheringTitle@@", model.Title);
            dynamic response =await sg.client.mail.send.post(requestBody: mailSt.Get());
            CreateLog(response, toEmail);
        }

and I am calling it like this:
  _emailManager.SendCreationEmail(myEmail , model).Wait();

![image](https://cloud.githubusercontent.com/assets/964109/20556239/779b417e-b166-11e6-9d3a-981cdf07eeed.png)

**Comment by thinkingserious** [comment]
Hello @ashkansiroos,

I'm not sure what is happening here, but here are some things to try out:

1. I'm providing this link because I noticed you are using 4.5.1: https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#missing
2. For using templates, please check this out: https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#transactional_templates

To further assist, could you please answer the following:

1. How did  you install the library?
2. What are your `using` statements?

Thanks!

**Comment by thinkingserious** [comment]
Hi @ashkansiroos,

You might want to try using the latest version of this library (v9). Please let me know if you run into any issues.
