### ISSUE TITLE
Is there any way in C# code where we can specify webhook url?

### ISSUE THREAD

**Issue by NagnathK** [sendgrid/sendgrid-csharp#424]
Issue Summary

We have two modules in c# that are using sendgrid to send the mail. In one module, we implemented webhook to track the mail callback statuses and other module is just for sending mail and we don't need statuses back.

We also pass notificationId as custom argument along with the mail message and that notificationId, we check in webhook method. It works fine for module where we implemented this. But other module where we don't need statuses back, it fails. Why because, it checks for notificationId and as it doesn't get it, it throws error. 

We have specified webhook url in Settings - > Mail settings - > Event Notification tab on Sendgrid website. I believe this is generalize webhook url for both the modules and hence both the modules hits our webhook callback url.

Is there any way in code to specify webhook url for a specific module just like twilio(third party to make call and sms)?

Please let us know to if there is any other way to get it resolved.

Thanks in Advance,
Nagnath Katkar

**Comment by thinkingserious** [comment]
Hello @NagnathK,

Thanks for submitting a github issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
