### ISSUE TITLE
The code is too concrete

### ISSUE THREAD

**Issue by ch-hristov** [sendgrid/sendgrid-csharp#435]
#### Issue Summary

Please extract the important object information into interfaces cause otherwise I'm forced to use your implementations and cannot provide my own in an easy way.

**Comment by thinkingserious** [comment]
Thanks @ch-hristov,

I've added your vote to this issue: https://github.com/sendgrid/sendgrid-csharp/issues/403

**Comment by Jericho** [comment]
@ch-hristov: I posted a comment on issue 403 which I thought you might find useful: I suggested considering [StrongGrid](https://www.nuget.org/packages/StrongGrid/) which is an alternative .net client which implements an interface for easy mocking. (disclaimer: I'm the author of this library)

It also allows you to inject an httClient so that, it you prefer, you can mock the data returned from the API.
