### ISSUE TITLE
Mails are not sending after upgradation of account

### ISSUE THREAD

**Issue by sandeepbonds** [sendgrid/sendgrid-csharp#440]
#### Issue Summary

I was using this code and code was working fine. I was using free account and since my daily limit was exhaust, I upgraded the account. after that I am able to send the mails and getting response Message Ok instead of Accept (I was getting Accept earlier). Even nothing is showing on Dashboard.

Below is the response I am getting 

{SendGrid.Response}
    Body: {System.Net.Http.StringContent}
    Headers: {}
    StatusCode: OK
    body: {System.Net.Http.StringContent}
    headers: {}
    statusCode: OK

**Comment by thinkingserious** [comment]
Hello @sandeepbonds,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
