### ISSUE TITLE
Create .NET Web Forms Example

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#461]
See https://github.com/sendgrid/sendgrid-csharp/issues/401

**Comment by andrewchilcott** [comment]
I already have a .NET Web Forms application - see my latest post it's working in 8.0.5 but not yet in 9.4.1 - willing to discuss possibilities.

**Comment by thinkingserious** [comment]
Thats awesome @andrewchilcott, how can I help?

**Comment by andrewchilcott** [comment]
Elmer

I was about to approach you to see how I could get the application listed as a Sendgrid partner. I thought that I should upgrade it to 9.4.1 before I did this. That’s when I hit the problem in #462.

Once we have sorted that out, I will publish a demo application on Azure and let you have a login.

Andrew

**Comment by StephenBanksDotNet** [comment]
We are in the process of migrating an ASP.Net Web Forms application from v2 to v3 but could really benefit from a simple bit of sample code written for Webforms. 

Does anyone have ASP.Net Webforms code that sends email via Sendgrid v3 and obtains a return code for the transaction from the Sendgrid server that we can log?

Any help is very much appreciated!

**Comment by andrewchilcott** [comment]
Stephen

Please contact me at andrew.chilcott@stpsolutions.com<mailto:andrew.chilcott@stpsolutions.com>, I think that I have exactly what you need.

Andrew

**Comment by StephenBanksDotNet** [comment]
Thanks so much Andrew for the offer! I'm emailing you now :)

**Comment by mbernier** [comment]
@andrewchilcott is this something that could be included as a project example in the library?

**Comment by StephenBanksDotNet** [comment]
That would be great. I was planning to create something similar for the benefit of others. Every bit of code I have tried so far failed in various ways for a simple WebForms implementation where an email is sent and a response is received for logging/debugging purposes. Receiving a response to log is important so that if there are issues, we know what failed.

With several code samples I have tried, the email would get sent but then the page load would never really complete and the browser is essentially waiting forever.

Can't wait to get my hands on some Webforms c# code for reliably sending a Sendgrid email with a return result.

**Comment by andrewchilcott** [comment]
Stephen

Please bear with me as I am currently on holiday in France. If I get the chance in the next couple of days I will answer you in more detail.

Andrew

**Comment by thinkingserious** [comment]
Thanks for helping out @andrewchilcott!

@StephenBanksDotNet,

In the mean time, if you change:

```csharp
var response = await client.SendEmailAsync(msg);
```

to 

```csharp
var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
```

your app should behave as expected.

With Best Regards,


Elmer

**Comment by andrewchilcott** [comment]
Stephen

I created the application that I have for my son’s estate agency business. They send out about 150,000 emails per month. Most of these are email alerts for various properties together with a weekly email and then individual emails for account welcome, verification, reset password etc.

I started using Sendgrid some three years ago and for much of that time used the simple smtp service. A year ago I decided to move to the v3 API. I have built out the functionality separately to my son’s site and he now just uses my components. I am intending to launch this commercially in the next few months.

What I have is a WebForms front end written in c# and using Bootstrap for the css. I have developed classes specifically for the front-end. The data to populate these classes comes from a web service I have built. The web service takes in data from the front-end, converts it into sendgrid classes, does the v3 api call to sendgrid, gets the response and returns it to the front-end together with a user message indicating the response from sendgrid so that this can be displayed to the user.

I hit the same problem as you with the page appearing to hang. Elmer Thomas from Sendgrid sorted this out. You have to add .ConfigureAwait(false) on all calls to the v3 api.

There are some added complications with using the v3 api in that permissioning is at an extremely granular level and also the functionality is seemingly endless in terms of what you can do with personalization.

I therefore chose to build my front end pages that could create a complex, personalized interface but could be vastly simplified by removing various permissions from the user. The UI is therefore heavily dependent on the permissions that the current user has.

You have no doubt come across the problem of getting emails to appear the same on all devices and screen sizes. Although Sendgrid have good templating functions I have found that the best way to use them is to use the template(all set up with multiple layers of tables and inline CSS) as the ‘Brand Template’ setting out the overall layout and styles. I then use my own template functions to create content templates for standard emails and alerts (which can also be personalized).

My very basic user screen can send a bulk email in three clicks. Select the message template (or add new content), select the recipient list (or add recipients manually) and send. There are other options for selecting different brand templates, amending the settings and scheduling the send (my permissioning extends to which user can select which messages and which recipient lists etc..)

As you would expect with the above customization, there has to be an Admin screen for managing permissions and settings and merging these with sendgrid’s own settings.

I have also built a a webhook parser, whereby I collect all of the events delivered, dropped, bounced, spam reported, unsubscribe, group unsubscribe etc.. I have developed some simple classes that can be called from a scheduled job so that the user’s CRM system can be synchronised to remove items that appear on the Sendgrid suppression lists.

I am not certain from your website whether you are targeting individuals (where most or all of the above may be over the top) or businesses to which my code would be very applicable.

Please let me know if any of the above is of interest.

Andrew

**Comment by thinkingserious** [comment]
@StephenBanksDotNet @andrewchilcott,

We have updated our [TROUBLESHOOTING section](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#ui-requests) to explain why this issue happens and its solution.

Thanks!

With Best Regards,

Elmer
