### ISSUE TITLE
Cancel a scheduled mail using X-Message-Id

### ISSUE THREAD

**Issue by ankit2771991** [sendgrid/sendgrid-csharp#488]
Is their any way to cancel a schedule mail using X-Message-Id instead of assigning a batch id to mail and then sending a cancel request using the batch id.

**Comment by thinkingserious** [comment]
Hello @ankit2771991,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
