### ISSUE TITLE
SendGridMessage.AddAttachment now requires Base64 encoded content

### ISSUE THREAD

**Issue by carlmwright** [sendgrid/sendgrid-csharp#511]
We just upgraded from v6.1 to v9.7.

It seems that the SendGridMessage that is now in the SendGrid.Helpers.Mail namespace has changed in a breaking way internally, but not externally.

Content that is passed in to the AddAttachment method now has to be Base64 encoded. From our point of view this seems to be a completely gratuitous change that only results in errors when customers report invalid/garbled email attachments.

I didn't spot anything about this in the documentation and I wanted to add this issue here so that anyone experiencing the issue can find the solution faster than I did!

**Comment by thinkingserious** [comment]
Hi @carlmwright,

Thanks for taking the time to provide feedback!

Could you please let me know what documentation you were looking at? Here is our official [attachment example](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments).

As for including this as part of the library, please take a moment to [upvote this issue](https://github.com/sendgrid/sendgrid-csharp/issues/248). Thanks!

With Best Regards,

Elmer

**Comment by carlmwright** [comment]
Hi,

There was a document about moving from V2 to v3, I think, but I can't see it now.

The main problem for me was that the SendGridMessage.AddAttachment used to take string name, string content the same as it does now, but content now has to be base64 encoded, whereas it used to do this internally.

**Comment by thinkingserious** [comment]
@carlmwright,

Was it [this](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#migrating)?

**Comment by Jericho** [comment]
@carlmwright If you are willing to consider an alternative to SendGrid's official .net client, I suggest you take a look at StrongGrid (disclaimer: I'm the author). The reason I make this suggestion is because it automatically handles most details about attachment handling such as base64 encoding, determining the MIME type, determining if an attachment must be displayed inline, etc.

Here's a small code sample to show how to attach a file to an email sent with StrongGrid:

```
var attachments = new[]
{
    SendGridAttachment.FromLocalFile("C:\\temp\\Receipt.pdf")
};

var client = new Client("... your api key...");
var messageId = await client.Mail.SendToSingleRecipientAsync(
        new MailAddress("bob@example.com", "Bob Smith"),
        new MailAddress("sales@ficticiouscompany.com", "The Sales Team"),
        "Receipt for your recent order",
        "<b>Thank you</b> for your recent purchase. Attached is a copy of your receipt",
        "Thank you for your recent purchase. Attached is a copy of your receipt",
        true,
        true,
        null,
        null,
        attachments)
    .ConfigureAwait(false);
```

Please note that `FromLocalFile` will take care of loading the file, base64 encoding the content, determining the MIME type and this attachment will be added to the outgoing email. Similarly, you could create an attachment from a stream using `SendGridAttachment.FromStream` and create an attachement from binary data using `SendGridAttachment.FromBinary`. 

Hopefully this is helpful to you

**Comment by shortstuffsushi** [comment]
Would there be interest in having this re-implemented and pull requested? In my case, I'm interested in being able to add an attachment stream, so an additional method overload. I would be willing to do the work if you would be interested in including it in the project.

**Comment by thinkingserious** [comment]
Hi @shortstuffsushi,

That sounds great, we would love a PR! Please let me know how I can help.

With Best Regards,

Elmer

**Comment by thinkingserious** [comment]
Please see [here](https://github.com/sendgrid/sendgrid-csharp/pull/522).
