### ISSUE TITLE
Not able to install sendgrid 9.9.0 on VS 2015 project

### ISSUE THREAD

**Issue by SauravHigh** [sendgrid/sendgrid-csharp#637]
Hi,
I am using trial version of sendgrid for 1 month and have created account for that, but while installing the sendgrid thorugh nuget it says 

Could not install package 'Sendgrid 9.9.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework.

Can you please help me into this 

Thanks

**Comment by thinkingserious** [comment]
Hello @SauravHigh,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Hello @SauravHigh,

That version of .NET is not supported. Please see [here](https://github.com/sendgrid/sendgrid-csharp/blob/master/TROUBLESHOOTING.md#net45).

Thanks!

With Best Regards,

Elmer
