### ISSUE TITLE
how to display web page in inside email body using external url

### ISSUE THREAD

**Issue by liberoram** [sendgrid/sendgrid-csharp#649]
I need to display web page in email (not to send html of page in email) like iframe, (not working in email).

If I used file_get_contents not working properly (showing css issues) (both are not wokring in email).

From my research / knowledge , I didn't found any possible ways, but is there any hack, that might possible to make this happen.

Please help me on this.

**Comment by thinkingserious** [comment]
Hello @liberoram,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
