### ISSUE TITLE
Html IFrame tag is not working in email body using php (codeigniter)

### ISSUE THREAD

**Issue by liberoram** [sendgrid/sendgrid-csharp#650]
I need to send a HTML iframe tag inside an email body.The HTML file  is working fine in a browser. But when i send it inside email body,  iframe tag is not getting interpreted so does not show in the body. How  can I send an iframe in email body.

Thanks in advance.

**Comment by thinkingserious** [comment]
Hello @liberoram,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
