### ISSUE TITLE
No email is sent when recipient email is duplicated

### ISSUE THREAD

**Issue by BotanMan** [sendgrid/sendgrid-csharp#691]
#### Issue Summary

When I have duplicates in `To` list no emails is sent, and no error is thrown

#### Steps to Reproduce

```
message.AddTo('igor@gmail.com');
message.AddTo('igor@gmail.com');

var client = new SendGridClient('....api-key...');
await client.SendEmailAsync(message);
```

#### Technical details:
* sendgrid-csharp Version: 9.9.0
* Platform ASP.NET
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hi @BotanMan,

The underlying API does not support sending duplicate emails. I will leave this open so that we may throw an appropriate error.

Thanks!

With Best Regards,

Elmer

**Comment by Jericho** [comment]
This seems to be an issue that several people face: [I found 9 issues on this topic](https://github.com/sendgrid/sendgrid-csharp/issues?utf8=%E2%9C%93&q=400+409+425+448+451+503+520+678+691).

Since this seems to be such a common issue, I added a new feature in the [StrongGrid](https://www.nuget.org/packages/StrongGrid/) library to automatically filter out duplicate recipients.

**Comment by BotanMan** [comment]
@Jericho @thinkingserious 
Yeah, but the strangest thing that in that case there is no way to understand that it won't work, no emails, no exceptions. it would be nice to have exception at least.

**Comment by Jericho** [comment]
@BotanMan I agree. SendGrid should either automatically filter out duplicates or throw an exception. But in the mean time, the only alternative we have to to detect and remove duplicate ourselves. That's why I added this feature to StrongGrid. If SendGrid fix their faulty behavior, the feature I just added will become obsolete but in the mean time I think it's the best solution. Do you agree?

Bottom line is: you are absolutely right that it doesn't make sense for SendGrid to refuse to send our email and not give us any feedback.

**Comment by RodgerLeblanc** [comment]
I'll work on this one, do you guys have a preference between [throwing an exception](https://github.com/sendgrid/sendgrid-csharp/issues/691#issuecomment-386762171) or [filtering the recipients/emails silently](https://github.com/sendgrid/sendgrid-csharp/issues/691#issuecomment-386918901)?

I'm a speaker at an Hacktoberfest event, is it okay if I delay my PR until October 4th in order to do it live on stage?

**Comment by childish-sambino** [comment]
Submitted #991 which will ignore duplicate email addresses (case-insensitive, email-only comparison) when serializing the message body.
