### ISSUE TITLE
Can't add custom header, MakeRequest not virtual

### ISSUE THREAD

**Issue by keodime** [sendgrid/sendgrid-csharp#697]
I was trying to add a header to the httpcall made by SendEmailAsync. By looking to the SendGridClient class, over the MakeRequest is written : "Make the call to the API server, override for testing or customization", but the call isn't virtual. 

Is there any other way to add an header to the call by using SendEmailAsync ? 
Am I missing something here ?

#### Technical details:
sendgrid-csharp Version: 9.9.0
Platform ASP.NET Core
netstandard2.0

**Comment by thinkingserious** [comment]
Hello @keodime,

Have you tried the `[AddHeader](https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#kitchensink)` method?

You can also add request headers using the [constructor](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/SendGridClient.cs#L121).

I hope that helps.

With Best Regards,

Elmer

**Comment by psboies** [comment]
Hi @thinkingserious ,

We have tried the addHeader method but it does not add the header for the call SendEmailAsync().
We are trying to stub that call for automated tests and it is required to add a correlation id in the headers so the stub service can identify the right test scope. 

We prefer not add the header through the constructor since we are using dependency injection and the correlation id is not set in the scope when we are setting the classes.

When we saw in the comments that it was possible to override the method MakeRequest, we thought we had finally a solution, but unfortunately, the call is not virtual.

Thanks for your help,

Phil

**Comment by thinkingserious** [comment]
@psboies,

So it sounds like what we need is to add a `addHeader` method directly to the SendGrid client. Would that solve your challenge?

With Best Regards,

Elmer

**Comment by psboies** [comment]
Hi @thinkingserious ,

Thank you for your quick answer.

AddHeader on the client won't work since it's not thread safe. Our tests run in parallel and we can't guarantee that the correlation id will be the same between the time it is set and the time the request is sent since our SendGrid client is singleton. SendGrid client is set as singleton because it contains a private HttpClient that does not dispose itself and creating new instances every call would cause a memory leak. We need to control our header by request and not by client. So the only way to do so would be the make virtual the makeRequest call so we can overwrite it then add headers to the HttpResponseMessage request which is a thread safe variable.

Have a nice day,

Phil

**Comment by thinkingserious** [comment]
Thanks for the clarification @psboies!

I will leave this open and on our backlog for implementation.

This issue can gain traction with more votes/comments or a PR.

With Best Regards,

Elmer

**Comment by keodime** [comment]
Same here !

**Comment by thinkingserious** [comment]
Fixed by #702
