### ISSUE TITLE
Add netstandard 2.0 target

### ISSUE THREAD

**Issue by redoz** [sendgrid/sendgrid-csharp#710]
#### Issue Summary

The general recommendation now is to target netstandard 2.0: https://twitter.com/davidfowl/status/1008453902058917888

**Comment by xt0rted** [comment]
#601 does just this, but it's taking forever to get things reviewed or merged sadly.

One key part of that tweet is

>If a library is targeting a lower version of .NET standard, is there an advantage to adding a 2.0 target even if you don’t use any of the newer APIs? Or are you saying if you are creating a new library, we should save ourselves the trouble and just skip straight to 2.0?

>Both. The advantage is that the dependency graph is extremely simplified. The packages that all exist for netstandard 1.0 are effectively frozen and we’d like to push the ecosystem off them

**Comment by Jericho** [comment]
@redoz, I encourage you to take a look at [StrongGrid](https://www.nuget.org/packages/StrongGrid/), which is an alternative to the official SendGrid .net client, because it already multi-targets `net452`, `netstandard1.3` and `netstandard2.0` (disclaimer: I'm the author).

Also, to @xt0rted's point, you will see that issues in the [StrongGrid project](https://github.com/Jericho/StrongGrid) are discussed and resolved quickly and PRs are welcome and merged promptly.

**Comment by thinkingserious** [comment]
Hi @redoz,

This issue is still on our backlog, but as @Jericho mentioned, StrongGrid is a solid alternative. 

Please follow #601 for progress.

Thanks!

With Best Regards,

Elmer
