### ISSUE TITLE
ApyKey Rotation

### ISSUE THREAD

**Issue by alex-valchuk** [sendgrid/sendgrid-csharp#713]
I would like to rotate ApiKey from my AWS Lambda function.

Is it possible to Cretate/Update Api Keys programmatically?

**Comment by Jericho** [comment]
@alex-valchuk yes you can create and revoke API keys programmatically. As @thinkingserious pointed out, the documentation is available on SendGrid's web site but keep in mind that you will have to manually craft the appropriate HTTP call along with hand-crafting the expected JSON. SendGrid's C# client does not help you with this.

I would like to suggest that you take a look at [StrongGrid](https://www.nuget.org/packages/StrongGrid/), which is an alternative to SendGrid's C# client, because it has this functionality built-in (disclaimer: I'm the author). Here's a code sample demonstrating how simple it is to create a new API key with StringGrid:

```csharp
var apiKey = "... YOUR API KEY ...";
var strongGridClient = new Client(apiKey);
var apiKey = await strongGridClient .ApiKeys.CreateAsync("StrongGrid Integration Testing: new Api Key", new[] { "alerts.read", "api_keys.read" }, null, cancellationToken).ConfigureAwait(false);
```

**Comment by thinkingserious** [comment]
@alex-valchukl, @Jericho's suggestion is solid.

**Comment by alex-valchuk** [comment]
Thank you very much guys for your answers.
It helped me a lot
