### ISSUE TITLE
Undocumented API changes

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#721]
The API documentation for retrieving all IPs in a specified pool says that the JSON returned by the API looks like this (notice the content of the `ips` property is an array of strings):

```
{
  "ips":["167.89.21.3"],
  "pool_name":"new_test5"
}
```

this was true at some point but it's no longer the case. The JSON is now different and unfortunately this doesn't seem to documented. What we are now observing is the following JSON (notice the content of the `ips` property is an array of objects with `ip`, `start_date` and `warmup` properties):

```
{
  "ips": [
    {
      "ip": "xxx.xxx.xxx.xxx",
      "start_date": null,
      "warmup": false
    }
  ],
  "pool_name": "StrongGrid Integration Testing: updated name"
}
```

1. Are there any other recent changes in the API that are not yet documented?
2. Is there a changes log or any way for us to be kept informed of changes to the API?

**Comment by ksigler7** [comment]
Hey @Jericho - this is a great catch, as always, thanks! This is documented incorrectly and I've added a backlog item to update this in our API docs (so I am going to close this issue here).

1. No. I am digging now to figure out how this slipped through the cracks, but I am fairly sure this is an anomaly.
2. We document all changes to the API here: https://sendgrid.com/docs/release_notes.html
