### ISSUE TITLE
Update integration tests to utilize StopLight.io's Prism version v2.X

### ISSUE THREAD

**Issue by thinkingserious** [sendgrid/sendgrid-csharp#749]
#### Issue Summary

We use a mock server for integration/contract testing that is driven by our OpenAPI specification and StopLight.io's Prism service. The service is spun up utilizing the prism.sh script in this repo.

Before writing any code, we suggest you review our `CONTRIBUTING.md` file and propose your solution for discussion here in the comments. Thank you!

#### Aceptance Criteria

* we automatically use the latest v2.X version of Prism locally, in Travis CI and in Docker
* tests pass locally, in Travis CI and using Docker
* update `CONTRIBUTING.md` documentation, if necessary

#### Notes & References

* [Prism GitHub Repo](https://github.com/stoplightio/prism)

**Comment by tony-ho** [comment]
I propose the following solution using [StopLight's Prism Docker image](https://hub.docker.com/r/stoplight/prism/):
- update the testing instructions to run Prism locally using the Docker image instead of downloading and installing Prism
- run Prism in Travis CI using the Docker image as per https://docs.stoplight.io/testing/continuous-integration/travis
- provide a Docker Compose configuration to run Prism and the tests as a multi-container Docker application

This removes the need to maintain the scripts to download and install Prism and provides better consistency between testing locally and in Travis CI.

In addition, using the `stoplight/prism:latest` tag will ensure the latest version of Prism is used as long as StopLight maintains the Docker image.

**Comment by childish-sambino** [comment]
Closing as prism integration has been moved to https://github.com/sendgrid/sendgrid-oai
