### ISSUE TITLE
Discrepancies in Event Webhook documentation

### ISSUE THREAD

**Issue by Jericho** [sendgrid/sendgrid-csharp#792]
There's a very convenient [table](https://sendgrid.com/docs/for-developers/tracking-events/event/#event-objects) in the Event Webhook Reference that lists the properties you can expect for each type of webhook event. However, there seem to be some errors in the table that I would like to clear up. For instance:
- The table indicates that the `ip` attribute is valid only for the `opened` and `clicked` events but the description of this attribute says: `the IP address used to send the email. For open and click events, it is the IP address of the recipient who engaged with the email.` This leads me to believe the IP attribute is valid for all event types. Am I right?
- The `tls` field is not indicated as valid for any of the event types. Surely that's not correct.

**Comment by KoditkarVedant** [comment]
In addition to above, there is some inconsistency between the event parser documents. There is an another [chart](https://sendgrid.com/docs/API_Reference/Event_Webhook/event.html#-Event-objects) where I can see `smtp-id` is not applicable to `open` and `close` events whereas [table](https://sendgrid.com/docs/for-developers/tracking-events/event/#event-objects) referred by @Jericho shows that `smtp-id` is available to all events.

**Comment by thinkingserious** [comment]
cc @ksigler7

**Comment by KoditkarVedant** [comment]
@thinkingserious is there any updates on this?

**Comment by TrendyTim** [comment]
@SendGridDX 
Why is this still an issue ? 
The SMTP-ID in the table still says not available for open/click etc, but the example above it and the webhook test post both provide the smtp-id for all events. Do I seriously have to add SMTP-ID as a unique argument to outgoing mail just to be sure ill get access to it on all webhook events ?

The issue is 18months old it should not take that long to figure out which part needs correcting.

**Comment by childish-sambino** [comment]
Closing in favor of https://github.com/sendgrid/docs/issues/4865

I'll attempt to bump that ticket internally.
