### ISSUE TITLE
Sometimes  there is delay in receiving emails,How  can we reduce the delay to less than 2 minutes

### ISSUE THREAD

**Issue by jaiswati** [sendgrid/sendgrid-csharp#799]
#### Issue Summary

This happens on adhoc basis..
Sometimes  there is delay in receiving emails,How  can we reduce the delay to less than 2 minutes
#### Steps to Reproduce

Email is sent as follows along with attachment

 dynamic sg = new SendGridAPIClient(apiKey);
                Email from = new Email(sender);
                Email to = new Email(recipient);
                Content content = new Content("text/plain", body);
                Mail mail = new Mail(from, subject, to, content);

#### Technical details:

* sendgrid-csharp Version: v 8.04  ( we need to deploy in this version only)
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by kylearoberts** [comment]
Issues like this are best brought to support so they can take a look to see if something is wrong. I would recommend hitting up support [here](https://support.sendgrid.com). More than likely support will need some examples. I would recommend providing headers for the email in question if you can.

**Comment by thinkingserious** [comment]
Hello @jaiswati,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
