### ISSUE TITLE
Use SendGrid API Key in Arm Template

### ISSUE THREAD

**Issue by xyz92** [sendgrid/sendgrid-csharp#828]

**Comment by thinkingserious** [comment]
Hello @xyz92,

I'm not sure how you would access those application settings in your app. I suggest you reach out to Microsoft on that one. 

That said, I'll leave this issue open here for further investigation.

With Best Regards,

Elmer

**Comment by ChrisProlls** [comment]
I will reuse this post to submit my issue because it's the exact same title.
We create a Sendgrid account on Azure through an ARM Template.
I would like to create an API Key from the ARM template, and store it safely into my Key Vault.
Is that possible ? Or do we need a manual action to get the API Key ?
