### ISSUE TITLE
SenderNotAuthenticatedGroup Error

### ISSUE THREAD

**Issue by xyz92** [sendgrid/sendgrid-csharp#829]
I have a **to** email address which includes multiple recipients. When I tried sending email, it blocked sending email:

![microsoftteams-image](https://user-images.githubusercontent.com/6519992/47946172-4279c400-dec5-11e8-9971-2781b4e4c3b1.png)

Here is my code:

    
        private static void Main()
        {
            Execute().Wait();
        }

        static async Task Execute()
        {
            var apiKey = Environment.GetEnvironmentVariable("SENDGRID_APIKEY");
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("noreply@xyz.com", "ABC DEF");
            var subject = "Notification using SendGrid";
            var to = new EmailAddress("ddd@xyz.com", "GHI JKL"); //will change to AppReviewer/AppSubmitter
            var plainTextContent = "This is a test";
            var htmlContent = "test";
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);
        }

Here ddd@xyz.com contains 3 recipients. What am I doing wrong?

**Comment by Niladri24dutta** [comment]
@xyz92  Did you have the API key in this variable `SENDGRID_APIKEY` in your config file or environment variables?

**Comment by thinkingserious** [comment]
Hello @xyz92,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
