### ISSUE TITLE
What is needed Need to make the following sample to work.

### ISSUE THREAD

**Issue by CasperKvolle** [sendgrid/sendgrid-csharp#850]
What is need in the following screendump?
I have been sitting several days now and trying to make this code sample work but without any luck.
![image](https://user-images.githubusercontent.com/8735055/51622915-e197e000-1f37-11e9-9d2a-a9e0056dbf77.png)

I have put the 
![image](https://user-images.githubusercontent.com/8735055/51623114-45baa400-1f38-11e9-9f39-5b9f96b930f9.png)

BUT every time I try to make it run the error comes:

"Unauthenticated senders not allowed"

Any other information you want to share that is relevant to the issue being reported. Especially, why do you consider this to be a bug? What do you expect to happen instead?

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @CasperKvolle,

You will need to make sure that the credentials you are setting are getting set properly. If so, then I would try testing your key here: https://sendgrid.com/docs/API_Reference/api_v3.html. If it still does not work, please either create a new API Key or reach out to our [support team](https://support.sendgrid.com) so that they can investigate your account.

With Best Regards,

Elmer
