### ISSUE TITLE
Sendgrid not able to access template with API key showing Access forbidden.

### ISSUE THREAD

**Issue by srinivas252** [sendgrid/sendgrid-csharp#856]
#### Request returned status Code 401Body:{"errors":[{"message":"The provided authorization grant is invalid, expired, or revoked","field":null,"help":null}]}

Am writing java code to access my particular template in sendgrid free version account with API KEY 

#### Just run my below code

I want to access the template with body in my java code or rest call please help
#### Technical details:

* sendgrid-version 4.3.0
[Sendmail.txt](https://github.com/sendgrid/sendgrid-csharp/files/2831302/Sendmail.txt)

* Platform (java)
* jdk 1.8

**Comment by thinkingserious** [comment]
Hello @srinivas252,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
