### ISSUE TITLE
Creating a subuser with a username creating a % symbol cannot be deleted

### ISSUE THREAD

**Issue by dantheman999301** [sendgrid/sendgrid-csharp#865]
#### Issue Summary

If you create a subuser with a `%` symbol in the username, it cannot then be deleted, either through the API or through the app (which uses the API so not that surprising!)

I don't believe this issue is down to the C# library but it's where we noticed it.

#### Steps to Reproduce

1. Create subuser with a % symbol in the username
2. Try and delete the subuser, either through API or app.

#### Technical details:

v3 API. Don't think anything else is relevant.

**Comment by thinkingserious** [comment]
Hello @dantheman999301,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
