### ISSUE TITLE
Support for toLowerCase/toUpperCase Handlebars helpers?

### ISSUE THREAD

**Issue by winzig** [sendgrid/sendgrid-csharp#866]
This isn't strictly related to your C-Sharp library, but I didn't see another repo for things related to your templating system. You now support Handlebars substitution format. One thing that would be really nice is if you also could supply some Handlebars helpers to deal with casing on variables. E.g.:

```
<h1>We Want to {{MyVariable}}</h1>

<p>We would like to {{toLowerCase MyVariable}}!</p>
```

And then SendGrid would implement the `toLowerCase` Handlebars helper method (and ideally some others, like `toUpperCase`, etc. 

This way we could send you a capitalized template variable, and use it in other ways where the casing needs to be different, e.g. all lowercase. The most common use case is when we pass in verbs/nouns that we want to use in the subject and a header in the email (title case), and then later want to use the same variables mid-sentence, where we want to lowercase it.

**Comment by thinkingserious** [comment]
Hello @winzig,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
