### ISSUE TITLE
HTTP response code 403 on add recipient api call 

### ISSUE THREAD

**Issue by kpardo11** [sendgrid/sendgrid-csharp#867]
#### Issue Summary

I am trying to add recipients through the API but to no avail. I'm currently running these tests using a console application (.Net Core)

False
Completed
{"errors":[{"field":null,"message":"access forbidden"}]}

#### Steps to Reproduce

var client = new RestClient("https://api.sendgrid.com/v3/contactdb/recipients");
            var request = new RestRequest(Method.POST);
            request.AddHeader("content-type", "application/json");
            request.AddHeader("Authorization", "Bearer <<API_KEY>>");
            request.AddParameter("application/json", "[{\"email\":\"user@temp.com\",\"first_name\":\"user\",\"last_name\":\"user\",\"age\":25}]", ParameterType.RequestBody);
            IRestResponse response = client.Execute(request);

            Console.WriteLine(response.IsSuccessful);
            Console.WriteLine(response.ResponseStatus);
            Console.WriteLine(response.Content);

Even trying to run this directly from the API Documentation I am receiving the same error. My api key privileges are set to full access. I also tried recreating my API Key but i am still receiving the same 403 error.

**Comment by thinkingserious** [comment]
Hello @kpardo11,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by anubha1123** [comment]
I'm getting same issue. i have reached to support team as well but nothing happened.
how to solve that problem?
