### ISSUE TITLE
access forbidden

### ISSUE THREAD

**Issue by james1278** [sendgrid/sendgrid-csharp#871]
#### Issue Summary

When i call any API for SendGrid to get data getting access forbidden error.
I already give the full permission but still getting error.
I have paid account and also use full permission access key but still getting same issue and not find anywhere proper solution please provide proper way so i can manage easily.

#### Steps to Reproduce
I tired to using postman.
1. Added URl in to URL Part http://api.sendgrid.com/v3/messages?limit=10
2. Give a Bearer "API Key"
3. "Content-Type" : "application/json"

 
#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @james1278,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by anubha1123** [comment]
Hello,
I'm getting same issue...
Please help me
