### ISSUE TITLE
Locked out of my account due to IP address whitelisting

### ISSUE THREAD

**Issue by vincenzo84** [sendgrid/sendgrid-csharp#875]
Hi,

I can't login with my account because i changed the ip of my connection and now the new ip is not whitelisted.

I contacted SendGrid support (ticket 2088580), but i didn't receive a response.

Can you help me? it's urgent.

Thanks in advance

**Comment by thinkingserious** [comment]
Hello @vincenzo84,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by surftripph** [comment]
I don't get this.  You need to go to support.sendgrid.com to file a support ticket to whitelist your new IP. The website also needs you to log in.  How are you supposed to ever file a ticket? Where is the logic in that?

**Comment by thinkingserious** [comment]
Hello @surftripph,

Have you tried sending an email to support@sendgrid.com?

With best regards,

Elmer
