### ISSUE TITLE
email is processing status

### ISSUE THREAD

**Issue by mariontichadou** [sendgrid/sendgrid-csharp#883]
Issue Summary

We have a client who have made a purchase but this client has not received any confirmation email coming from the SMTP Sendgrid. 
I can see that this client email address have a PROCESSING status. 

What could be the reason why an email is still in "processing"? 
How can we solve this issue?

**Comment by thinkingserious** [comment]
Hello @mariontichadou,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
