### ISSUE TITLE
Feature request: test API Key (can only send e-mails to configured domains)

### ISSUE THREAD

**Issue by DaveAurionix** [sendgrid/sendgrid-csharp#898]
# SendGrid Feature Request

Sorry, not sure from the SendGrid site how to raise feature requests, I'm hoping a developer at SendGrid can raise this through the correct channel …

We use the C# SendGrid client a lot, but we'd like to create API keys for test environment purposes (as opposed to the production environment) that are locked down to only send to addresses in certain domains.

As a wider feature this could be the capability to lock down API key permissions to only send to addresses in selected contact lists or to configured domains.

**Comment by thinkingserious** [comment]
Hello @DaveAurionix,

Thank you for reaching out! I have passed along your feedback to the product team.

If there is any progress on implementing your suggested feature requests, we will post an update here.

In the mean time, for testing, you might find [`sandbox_mode`](https://github.com/sendgrid/sendgrid-csharp/blob/master/src/SendGrid/Helpers/Mail/Model/MailSettings.cs#L34) and/or our [Open API specification](https://github.com/sendgrid/sendgrid-oai) helpful.

I'm closing this out right now since the feature request not a helper library issue.

With best regards,

Elmer

**Comment by thinkingserious** [comment]
Tracking #: [CL-2681]
