### ISSUE TITLE
I'm getting error of access forbidden while fetching the list of campaigns

### ISSUE THREAD

**Issue by anubha1123** [sendgrid/sendgrid-csharp#911]
My code below: 
```
string apiKey =  Environment.GetEnvironmentVariable("SENDGRID_API_KEY");
            var client = new SendGridClient(apiKey);
            string queryParams = @"{
  'limit': 1, 
  'offset': 1
}";
            var response = await client.RequestAsync(method: SendGridClient.Method.GET, urlPath: "campaigns", queryParams: queryParams);
            Console.WriteLine(response.StatusCode);
            var ddd = response.Body.ReadAsStringAsync().Result;
            Console.WriteLine(response.Body.ReadAsStringAsync().Result);
            Console.WriteLine(response.Headers.ToString());
            Console.ReadLine();

```

**Error** 
**{"errors":[{"field":null,"message":"access forbidden"}]}**

i have given full access to key.

**Comment by thinkingserious** [comment]
Hello @anubha1123,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
