### ISSUE TITLE
How to add contact in the list?

### ISSUE THREAD

**Issue by anubha1123** [sendgrid/sendgrid-csharp#918]
Hello,
I'm trying to add contact in the list so i'm using this link below to **Add a Single Recipient to a List** :
https://github.com/sendgrid/sendgrid-csharp/blob/master/USAGE.md#contactdb

I have **Advanced 100k** plan and using full access api key but still getting forbidden error. 

Please help me out in this.

**Comment by thinkingserious** [comment]
Hello @anubha1123,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
