### ISSUE TITLE
How can I get the E-Mail after it's sent?

### ISSUE THREAD

**Issue by Yashuaa** [sendgrid/sendgrid-csharp#919]
This is not really a bug. I'm using SendGrid with C#. I have a Template that I have created and I build my e-mail based on this template. In C# I am using the SendGrid NuGet package and i set the email.TemplateId = "my-id-here"; Then I send my e-mail. Is there a way that I can actually view the e-mail after I send it though? I really just want to get the generated e-mail before I send it. Is that possible? I really want to avoid setting up a WebHook that shoots the e-mail to some other Web API I have to create and set up as that is extra unneeded work.

**Comment by thinkingserious** [comment]
Hello @Yashuaa,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
