### ISSUE TITLE
9.12.0 on nuget.org does not reflect master?

### ISSUE THREAD

**Issue by jnyrup** [sendgrid/sendgrid-csharp#920]
#### Issue Summary

The 9.12.0 package uploaded to Nuget.org does not reflect the source changes for 9.12.0.
Looking at the dependencies for https://www.nuget.org/packages/Sendgrid/9.12.0
`System.Net.Http` is still present for net40, which should also be net452
https://github.com/sendgrid/sendgrid-csharp/blob/02200e5e3171c49a0ed8cf2801346039be5f233c/src/SendGrid/SendGrid.csproj#L57-L59
Inspecting the [nupkg](https://www.nuget.org/api/v2/package/Sendgrid/9.12.0) has the same problem.

The source code at https://github.com/sendgrid/sendgrid-csharp/releases/tag/v9.12.0 looks fine, and when compiling it with:
```
dotnet build
dotnet pack
```
the generated `nuspec` file looks as expected.

**Comment by thinkingserious** [comment]
Hello @jnyrup,

Thanks for the heads up. We've added this issue to our backlog for further investigation.

I'm thinking that perhaps the metadata was not updated correctly, but the .dll's and associated files should contain the latest source changes.

With best regards,

Elmer

**Comment by jnyrup** [comment]
I just inspected the compiled dll from nuget and agree that the changes from e.g. #839 are present.

**Comment by StandBackBurrito** [comment]
I am running into an issue with the references to `System.Net.Http` in the current nuget package.

Since this is marked as help wanted I thought I would offer up some assistance. However I can't find any documentation on the release process, so I am not sure what I can do to help.

The travis file looks correct to me (when I run the steps locally I get the proper nugpkg) .

Is there any documentation on the release process, or is it even possible for the community to assist in the release process?

**Comment by jnyrup** [comment]
This has been resolved with some of the newest changes.
https://www.nuget.org/packages/Sendgrid/9.12.1 still had the problems.
https://www.nuget.org/packages/Sendgrid/9.12.5 does not have the problem.
