### ISSUE TITLE
Error is not clear

### ISSUE THREAD

**Issue by Yashuaa** [sendgrid/sendgrid-csharp#921]
#### Issue Summary
This error is not clear at all and I wasted two days trying to figure out what is going on. Whenever you send an e-mail to somebody and CC that same email address you will get this vague error.

BadRequest Connection: keep-alive Access-Control-Allow-Origin: https://sendgrid.api-docs.io Access-Control-Allow-Methods: POST Access-Control-Allow-Headers: Authorization, Content-Type, X-No-CORS-Reason: https://sendgrid.com/docs/Classroom/Basics/API/cors.html 

See my code below
```
Email = new SendGridMessage();

Email.SetFrom(Environment.GetEnvironmentVariable("SendGridFromEmail"));

Email.AddTo("developer@aol.com", "The Team");

bool developerIsUnitTesting = Environment.GetEnvironmentVariable("DeveloperUnitTesting") != null;
if (developerIsUnitTesting)
{
      Email.AddCc("developer@aol.com", "The Team");
}
```

#### Steps to Reproduce

1. Create a e-mail and send it to the same address that you CC

#### Technical details:
ASP.NET

**Comment by Jericho** [comment]
This is a known issue with SendGrid's API and you are not the only one to report it. It's discussed [here](https://github.com/sendgrid/sendgrid-csharp/issues/896) and [here](https://github.com/sendgrid/sendgrid-csharp/issues/678).

If I may make a suggestion: you should try [StrongGrid](https://www.nuget.org/packages/StrongGrid/) which is an alternate C# client for SendGrid's API (disclaimer: I'm the author). One of the features of StrongGrid is that it automatically de-duplicates recipients in order to avoid this problem.

**Comment by Yashuaa** [comment]
@Jericho Ok, I'll check it out. Thanks man

**Comment by thinkingserious** [comment]
Hello @Yashuaa,

Please follow [this issue](Yashuaa) for progress.

Thanks for jumping in and helping out @Jericho!

With best regards,

Elmer
