### ISSUE TITLE
SendGridClient should be created if there's no valid key

### ISSUE THREAD

**Issue by gethari** [sendgrid/sendgrid-csharp#923]
#### SendGridClient accepting null or empty ApiKey values

Create a new SendGridClient with the below code snippet.

#### Steps to Reproduce

1. Install Nuget package
2. Use the below piece of code

```
var apiKey = string.Empty;
var client = new SendGridClient(apiKey);
```

```
string apiKey = null;
var client = new SendGridClient(apiKey);
```

The client gets created and proceeds for further execution on both the above pieces of code.

**Expected Behavior :**
Exception must be thrown if the key is null or empty.

#### Technical details:

* sendgrid-csharp Version: 9.12.0
* Platform : Console App , NETFramework
* .NET Version:  Version=v4.6.1

One of my collegue tried this from a FunctionApp as well, this occurs there as well. I guess since there's no validation applied on the apiKey param.

**Comment by aevitas** [comment]
Thanks for reporting this - as far as I know this is indeed a bug and the `SendGridClient` should throw an `ArgumentNullException` if the `apiKey` parameter is omitted. 

The constructor in question delegates to the `SendGridClient(HttpClient httpClient, SendGridClientOptions options)` ctor, which does check for `options` to be non-null, but not any of its members. 

Definitely something that should be fixed in my opinion.

**Comment by childish-sambino** [comment]
Taking a look at the submitted PR.
