### ISSUE TITLE
Please add an interface on the SendGrid.Helpers.Mail.EmailAddress object

### ISSUE THREAD

**Issue by hroger1030** [sendgrid/sendgrid-csharp#925]
#### Issue Summary

Please add an interface on the SendGrid.Helpers.Mail.EmailAddress object. This will allow your users to pass in existing objects that implement the interface, rather than having to write a bunch of code to copy fields into a new instance of your Email object.

 
namespace SendGrid.Helpers.Mail
{
    public class EmailAddress : IEmailAddress
    ...

Doesn't have to be fancy, just something really simple and clean like:

    public interface IEmailAddress
    {
        string Email { get; set; }
        string Name { get; set; }
    }

Thanks!

**Comment by RodgerLeblanc** [comment]
I'll work on this one

**Comment by RodgerLeblanc** [comment]
While implementing this, I realized that adding this interface will introduce breaking changes. Take this code as an example : 
```csharp
public class Personalization
{
    public List<IEmailAddress> Tos { get; set; }
    //...
}
```

The fact that `Personalization.Tos` must change its definition from `List<EmailAddress>` to `List<IEmailAddress>` makes it a breaking change. For instance, if someone had this code in their app, the code would not compile anymore : 
```csharp
List<EmailAddress> emails = personalization.Tos; //Used to return a list of EmailAddress objects
```

Here's the list of breaking changes this feature would introduce : 
- Personalization.Tos changes from `List<EmailAddress>` to `List<IEmailAddress>`
- Personalization.Ccs changes from `List<EmailAddress>` to `List<IEmailAddress>`
- Personalization.Bccs changes from `List<EmailAddress>` to `List<IEmailAddress>`
- SendGridMessage.From changes from `EmailAddress` to `IEmailAddress`
- SendGridMessage.ReplyTo changes from `EmailAddress` to `IEmailAddress`

**Comment by aevitas** [comment]
Apart from being a breaking change, `EmailAddress` is a fairly simple type whose only purpose is to carry a little bit of data. I don't think adding abstractions for DTOs is a very good design choice, especially when the alternative is as simple as assigning two properties.

**Comment by hroger1030** [comment]
You are thinking of an email address as a descret object, why would that be
true? Does it have to impliment only two properties?

Couldn't it also be properties hanging off a customer object? By turning
this into an interface, you are decoupling the code from the requirements
of using that specific object, and allowing the caller to pass you anything
that meets the requirements of the contract.

You are just assuming that all the users are willing and capable of using
the provided email container object.

**Comment by aevitas** [comment]
On the consumer end, it could be attach to any type of object and could be modeled in any way you'd like. From a library point of view, `EmailAddress` is simply a data transfer object, and should be modeled as such.

Your proposed change follows a more compositional design, where for instance a `Customer : IEmailAddress, IBillingAddress` could be passed between your code and a library freely. I think you should be careful with design choices such as these, because not only are you introducing dependencies on external libraries by having your core data types implementing interfaces from them, it's also not very good interface design.

Interfaces are a language construct designed to allow you to write multiple implementations for them, and things such as e-mail addresses, billing addresses, or customers don't tend to have more than one implementation in your code.

It's a breaking change, and breaking changes should be considered in the overall design carefully, and I don't think this breaking change can be warranted if all it does is saving someone the time of writing an extension method along the lines of:

```csharp
public static EmailAddress ToEmailAddress(this Customer customer)
{
   return new EmailAddress(customer.Name, customer.EmailAddress();
}
```

to cross the boundries between consumer and library code.

**Comment by childish-sambino** [comment]
Closing as "won't fix". I agree with the comment above by @aevitas .
