### ISSUE TITLE
Using Transactional Template in SMTP client instead of send grid client.

### ISSUE THREAD

**Issue by kunalpgithub** [sendgrid/sendgrid-csharp#943]
#### Issue Summary

I am using send grid client to send email in my application, but for my test environment, I am using mailtrap.  Now we are also using Transactional Template from the send grid also. There is no way I can pass this template to a mail I am sending using SMTP client for mail trap.

#### Steps to Reproduce

Create SMTP Client to send email
Try to assign a transactional template to the message body of SMTP Client.

#### Technical details:

* sendgrid-csharp Version: master (latest commit: [commit number])
* Platform (WebForms, ASP.NET, ASP.NET Core, etc.)
* .NET Version: 4.5.2

**Comment by thinkingserious** [comment]
Hello @kunalpgithub,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
