### ISSUE TITLE
Multiple emails in Essentials plan

### ISSUE THREAD

**Issue by nicolaskoopol** [sendgrid/sendgrid-csharp#944]
Hello

Is there any restriction on the number of to, cc, bcc in Essentials mode?

Using this mode, I can send an email to a specific adress and add one CC or on BCC but as soon as I add another target, I receive a Bad Request 400 error.

It is maybe related to feature "No Subuser Management" which mentions "unable to segment your sends"??

Should I upgrade my pricing plan to be able to do this?

Thanks in advance,

Nicolas

**Comment by thinkingserious** [comment]
Hello @nicolaskoopol,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
