### ISSUE TITLE
How to use transactional template 

### ISSUE THREAD

**Issue by FaizaNasir** [sendgrid/sendgrid-csharp#953]
How to use transactional template from asp.net c# to pass certain data from the app into the template.
So I have made a transactional template in my sendgrid now i wish to utilize it in my code and pass a dynamically created url into the button of the template.
I am new to sendgrid. 
Any help shall be appreciated

**Comment by thinkingserious** [comment]
Hello @FaizaNasir,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
