### ISSUE TITLE
Binding sendgrid Html Table to json dataset?

### ISSUE THREAD

**Issue by patricknolan** [sendgrid/sendgrid-csharp#957]
Hi,

I need to set the variable in an email template to a json dataset and then bind this to a Html Table. Would you be able to advise me if this possible with SendGrid and if so would you have any examples?

**Comment by patricknolan** [comment]
Could anyone help here?

**Comment by thinkingserious** [comment]
Hello @patricknolan,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
