### ISSUE TITLE
Where are the documentation?

### ISSUE THREAD

**Issue by lordlycastle** [sendgrid/sendgrid-csharp#974]
#### Issue Summary

I can't find where the docs are located for the SendGrid library. For example I want to find out valid values for Type of Attachment class but can't seem to find it anywhere.

Does this exist?

**Comment by lordlycastle** [comment]
What happens if you give both html and plain text content? Is only one used? Where is the doc on this?

**Comment by prayatna** [comment]
hope this helps https://github.com/sendgrid/sendgrid-csharp/blob/master/USE_CASES.md#attachments

**Comment by thinkingserious** [comment]
Hello @lordlycastle,

As @prayatna (thank you!) pointed out, you can find the documentation on attachments at the link provided. You may also find API reference documentation [here](https://sendgrid.com/docs/API_Reference/api_v3.html).

With regards to html and plain text content, if you provide both, most email clients will render the html version. The plain text version is displayed if there is no html renderer. We advise including both because we have observed having both be a positive factor in avoiding SPAM filters. For more on that topic, please see [this link](https://sendgrid.com/blog/top-10-tips-and-tricks-to-stay-out-of-the-spam-folder-2-0/).

Thank you!

With best regards,

Elmer
