### ISSUE TITLE
get message id /w domain it was sent from

### ISSUE THREAD

**Issue by jimmywarting** [sendgrid/sendgrid-csharp#984]
I would like to use `message://<message-id>` to help user quickly open up our verification email for an easier onboarding

When I send a mail with the api get a response header including `x-message-id: xxxxx` but the link don't work unless i have the origin domain in there also.

i tried adding `@ismtpd0004p1lon1.sendgrid.net` at the end also but it keeps changing subdomain all the time.
would it be possible to also get the slave-domain of which origin it was sent from (or going to be sent from) also?

**Comment by thinkingserious** [comment]
Hello @jimmywarting,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team

**Comment by thinkingserious** [comment]
Hi @jimmywarting,

Are you having difficulty contacting our support team?
