### ISSUE TITLE
API incorrectly reports "Cannot use dynamic template data with a legacy template ID"

### ISSUE THREAD

**Issue by catdsnny** [sendgrid/sendgrid-csharp#988]
#### Issue Summary

C# development using REST service or nuget obtained wrapper - I suspect this is not specifically limited to C# implementations because the error is being returned from the server.

#### Steps to Reproduce

Create an API key with limited access

Make a REST based call to the V3 endpoint and select a dynamic template ID as the source.  Verify that the template is not a legacy template.

Observe error returned as "Cannot use dynamic template data with a legacy template ID"

Modify API key permission to "full access" in the SG portal.

Observe that no error is returned and mail sends correctly.

#### Technical details:

* sendgrid-csharp Version: doesnt really matter as this is a server side issue
* Platform any
* .NET Version: 4.5.2

**Comment by childish-sambino** [comment]
Just tried this and I'm getting the proper error: `Authenticated user is not authorized to send mail`. If you're still seeing it then best to contact support to debug a specific request.

**Comment by thinkingserious** [comment]
Hello @catdsnny,

Thanks for submitting a GitHub issue! We are very sorry that you are running into this problem. In order to better serve you, as this does not present itself as a library specific issue, we would like to ask that you reach out to our support team at <a href="https://support.sendgrid.com">https://support.sendgrid.com</a>.

Thank you!

SendGrid DX Team
