### ISSUE TITLE
i have to maintain the email status and resend it if emails are failed while using the  transportWeb.Deliver(message);

### ISSUE THREAD

**Issue by swapnilmahangare** [sendgrid/sendgrid-csharp#99]
below code i am using
var message = new SendGridMessage();
            message.AddTo(mailAddressIdentity.AddTo);
            message.From = new MailAddress(mailAddressIdentity.FromAddress, mailAddressIdentity.FromDisplayName);
            message.Subject = mailAddressIdentity.Subject;
            message.Html = "<p> </p>";
            message.EnableTemplateEngine(Convert.ToString(ConfigurationManager.AppSettings["SendGridTemplateKey"]));

            message.EnableTemplate("<p> <% body %> </p>");

            var identifiers = new Dictionary<string, List<string>>();

            identifiers.Add("-user-", new List<string> { mailAddressIdentity.ToName });
            identifiers.Add("-link-", new List<string> { linkUrl.Replace("strURLToken", linkUrl) });

            foreach (var identifier in identifiers) {
                message.AddSubstitution(identifier.Key, identifier.Value);
            }
           
            message.EnableClickTracking();
            message.DisableSpamCheck();
            message.EnableGravatar();
            message.DisableUnsubscribe();
            message.EnableOpenTracking();
            message.GetEmbeddedImages();
            var credentials = new NetworkCredential(Convert.ToString(ConfigurationManager.AppSettings["SendGridUserName"]), Convert.ToString(ConfigurationManager.AppSettings["SendGridPassword"]));
            var transportWeb = new Web(credentials);
            try {
                 transportWeb.Deliver(message);

            } catch (Exception ex) {
}

i have to maintain the email status whether it is failed or successfully sent and if email are failed than while using that failed list i need to resnd the emails . please help me out

**Comment by smurfpandey** [comment]
You can use [Event Webhooks](https://sendgrid.com/docs/API_Reference/Webhooks/event.html)

**Comment by ravvenukam** [comment]
Hi We are also facing the same issue. transportWeb.Deliver(message); is not throwing any exception but sendgrid is saying they didn't receive any request. This is not happening for all the emails ,this is happening once in a while may be 5%. If you didn't receive email request what will be return response of transportWeb.Deliver(message) ???

**Comment by MarcelloCarreira** [comment]
Hello, I also believe that transportWeb should return some information from the server when it successfully have delivered the message to the api. I know this is not the same as knowing if the message itself was delivered to the recipient (this is done using the Webhooks). But this information is indeed very useful, because you can retry sending the message to the api if you got an error. For example, I sometimes try to deliver a message, but I got an invalid api key, but the key is untouchable and also the code, the error is at the transport or at the api itself. So having an OK back message is crucial to have some peace. I forked the this C# rep, to have transportWeb.DeliverAsyncReturn() but I would love to see it in the official one.

**Comment by aserdaray** [comment]
@MarcelloCarreira  Definetly you are right . But SendGrid's developers are so lazy. When i asked this kind of bug. They suggests try catch block. In this case, we start to implement  v3 and smtp api from the beginning bcoz. This project is not useful. We will sent over 100.000 mail per month.

**Comment by thinkingserious** [comment]
This is on our roadmap.
